export const MILITARY_BALANCE = {
  organizationRetreatThreshold: 18,
  moraleRetreatThreshold: 22,
  dailyOrganizationRecovery: 6,
  dailyMoraleRecovery: 2.5,
  dailyReinforcementRate: 12,
  reinforcementGoldPerMan: .012,
  reinforcementIronPerMan: .002,
  reinforcementToolsPerMan: .0015,
  lowSupplyThreshold: .75,
  criticalSupplyThreshold: .4,
  lowSupplyCombat: .82,
  criticalSupplyCombat: .58,
  lowSupplyMovement: .8,
  criticalSupplyMovement: .55,
  criticalAttritionRate: .002,
  fortDefensePerLevel: .12,
  maximumFortDefense: .6,
  dailyBaseCasualtyRate: .018,
  dailyBaseOrganizationDamage: 12,
  experienceGainPerDay: .35,
} as const;
