import {describe, expect, it, vi} from 'vitest';
import {countries, provincesData} from '../../data/map';
import type {War} from '../../types';
import type {AirState, AirCombatReport} from '../../types/air';
import {AIR_COMBAT_INACTIVITY_DAYS, AIR_COMBAT_HISTORY_LIMIT} from '../../types/air';
import {airCombatTick, assignAirMission, createInitialAirState, airZoneByProvinceId, airZones, type AirContext} from '../air';
import {readAirSave} from '../air/save';
import {advanceAirCombatReports, airCombatReportToast, createAirCombatReport, finishAirCombatReport, updateAirCombatReport, limitAirCombatHistory} from '../air/reports';
const initial=createInitialAirState(countries,provincesData);
const bra=initial.wings.find(w=>w.countryTag==='BRA')!, arg=initial.wings.find(w=>w.countryTag==='ARG')!;
const zone=airZoneByProvinceId.get(bra.baseProvinceId)!;
const war:War={id:'air-v11',attacker:'BRA',defender:'ARG',startDate:{year:1444,month:11,day:11},warScore:0,attackerCasualties:0,defenderCasualties:0,occupiedByAttacker:[],occupiedByDefender:[]};
const ctx:AirContext={countries,provinces:provincesData,wars:[war],relations:[]};
const wings=[bra,arg].map(w=>assignAirMission(w,'AIR_SUPERIORITY',zone.id,ctx)!);
const state=():AirState=>({wings:structuredClone(wings),engagements:[]});
const tick=(s:AirState,day:number,onEnded?:(report:AirCombatReport)=>void)=>airCombatTick(s,ctx,day,onEnded);
const quiet=(s:AirState,day:number,onEnded?:(report:AirCombatReport)=>void)=>airCombatTick(s,{...ctx,wars:[]},day,onEnded);
const snapshots=[{wingId:'known',wingName:'Fighter',countryTag:'BRA',type:'FIGHTER' as const,mission:'AIR_SUPERIORITY' as const,initialAircraft:24,finalAircraft:21,aircraftLost:3}];

describe('Air Combat Reports V1.1 lifecycle',()=>{
  it('creates ACTIVE with first and last combat day',()=>{expect(tick(state(),10).reports![0]).toMatchObject({status:'ACTIVE',startedAt:10,lastCombatDay:10});});
  it('updates the same ID across continuous combat without a second report',()=>{const first=tick(state(),10),second=tick(first,11),third=tick(second,12);expect(third.reports).toHaveLength(1);expect(third.reports![0].id).toBe(first.reports![0].id);expect(third.reports![0].lastCombatDay).toBe(12);});
  it('keeps initial counts and metadata while final counts and losses accumulate',()=>{const first=tick(state(),10);const before=structuredClone(first);const second=tick({...first,wings:first.wings.map(w=>({...w,name:'Renamed'}))},11);const r=second.reports![0];for(const p of r.participants){const original=first.reports![0].participants.find(o=>o.wingId===p.wingId)!;expect(p.initialAircraft).toBe(original.initialAircraft);expect(p.wingName).toBe(original.wingName);expect(p.finalAircraft).toBe(second.wings.find(w=>w.id===p.wingId)!.aircraftCount);expect(p.aircraftLost).toBe(original.aircraftLost+second.engagements[0].losses[p.wingId]);}expect(first).toEqual(before);});
  it('adds daily losses 3 + 2 + 1 exactly once and derives country/type totals',()=>{const first=createAirCombatReport('known',zone.id,10,snapshots);const second=updateAirCombatReport(first,11,[{...snapshots[0],initialAircraft:21,finalAircraft:19,aircraftLost:2}]);const third=updateAirCombatReport(second,12,[{...snapshots[0],initialAircraft:19,finalAircraft:18,aircraftLost:1}]);expect(third.participants[0]).toMatchObject({initialAircraft:24,finalAircraft:18,aircraftLost:6});expect(third.lossesByCountry).toEqual({BRA:6});expect(third.lossesByType).toEqual({FIGHTER:6});expect(third.totalAircraftLost).toBe(6);});
  it('counts replenishment losses independently from initial-final and round-trips them',()=>{const first=createAirCombatReport('known',zone.id,10,snapshots);const next=updateAirCombatReport(first,11,[{...snapshots[0],initialAircraft:30,finalAircraft:28,aircraftLost:2}]);expect(next.participants[0]).toMatchObject({initialAircraft:24,finalAircraft:28,aircraftLost:5});expect(readAirSave({wings:[],reports:[next]},ctx).reports).toEqual([next]);});
  it('keeps a destroyed wing snapshot on following ticks',()=>{const first=tick({wings:[{...wings[0],aircraftCount:1,maxAircraft:1},{...wings[1],aircraftCount:1000,maxAircraft:1000}],engagements:[]},10);expect(first.wings.some(w=>w.id===bra.id)).toBe(false);const second=tick(first,11);expect(second.reports![0].participants.find(p=>p.wingId===bra.id)).toMatchObject({initialAircraft:1,finalAircraft:0,aircraftLost:1});});
  it('adds a reinforcing wing to the same battle with its entry count',()=>{const first=tick(state(),10),reinforcement={...wings[0],id:'reinforcing',aircraftCount:12};const second=tick({...first,wings:[...first.wings,reinforcement]},11);expect(second.reports).toHaveLength(1);expect(second.reports![0].participants.find(p=>p.wingId==='reinforcing')).toMatchObject({initialAircraft:12,finalAircraft:12-second.engagements[0].losses.reinforcing});});
  it('separates simultaneous engagements in another zone',()=>{const other=airZones.find(z=>z.id!==zone.id)!;const extras=wings.map(w=>({...w,id:`other-${w.id}`,assignedAirZoneId:other.id}));const reports=advanceAirCombatReports([], [{zoneId:zone.id,wingIds:wings.map(w=>w.id),losses:{}},{zoneId:other.id,wingIds:extras.map(w=>w.id),losses:{}}], [...wings,...extras],10,new Map([['BRA',new Set(['ARG'])]]));expect(reports).toHaveLength(2);expect(new Set(reports.map(r=>r.zoneId))).toEqual(new Set([zone.id,other.id]));});
  it.each([1,2])('does not end after %i quiet days',days=>{const first=tick(state(),10),callback=vi.fn();expect(quiet(first,10+days,callback).reports![0].status).toBe('ACTIVE');expect(callback).not.toHaveBeenCalled();});
  it('ends after exactly three quiet days with endedAt on closure',()=>{let s=tick(state(),10);s=quiet(s,11);s=quiet(s,12);s=quiet(s,13);expect(AIR_COMBAT_INACTIVITY_DAYS).toBe(3);expect(s.reports![0]).toMatchObject({status:'ENDED',lastCombatDay:10,endedAt:13});});
  it('resumes after two quiet days without reopening or resetting initial counts',()=>{const first=tick(state(),10);const next=tick(quiet(quiet(first,11),12),13);expect(next.reports).toHaveLength(1);expect(next.reports![0].id).toBe(first.reports![0].id);expect(next.reports![0].status).toBe('ACTIVE');});
  it('never reactivates ENDED; later combat gets a new stable ID',()=>{const first=tick(state(),10),ended=quiet(first,13),next=tick({...ended,wings},14);expect(next.reports).toHaveLength(2);expect(next.reports![0]).toEqual(ended.reports![0]);expect(next.reports![1].id).toBe(`air-battle-14-${zone.id}`);expect(updateAirCombatReport(ended.reports![0],14,snapshots)).toBe(ended.reports![0]);});
  it('limits only ENDED and retains an older ACTIVE battle',()=>{const active=createAirCombatReport('active',zone.id,0,snapshots);const ended=Array.from({length:AIR_COMBAT_HISTORY_LIMIT+2},(_,i)=>finishAirCombatReport(createAirCombatReport(`ended-${i}`,zone.id,i+1,snapshots),i+2));const result=limitAirCombatHistory([active,...ended.reverse()]);expect(result).toHaveLength(AIR_COMBAT_HISTORY_LIMIT+1);expect(result).toContain(active);expect(result[0].id).toBe('ended-2');});
  it('restores ACTIVE save and continues the same report and accumulated losses',()=>{const first=tick(state(),10);const loaded=readAirSave(JSON.parse(JSON.stringify(first)),ctx);expect(loaded.engagements).toEqual([]);const next=tick(loaded,11);expect(next.reports).toHaveLength(1);expect(next.reports![0].id).toBe(first.reports![0].id);expect(next.reports![0].totalAircraftLost).toBe(first.reports![0].totalAircraftLost+Object.values(next.engagements[0].losses).reduce((s,n)=>s+n,0));});
  it('normalizes V1 single-tick reports as ENDED with a one-day period',()=>{const r=tick(state(),10).reports![0];const legacy={id:r.id,zoneId:r.zoneId,day:r.day,participants:r.participants};expect(readAirSave({wings:[],reports:[legacy]},ctx).reports![0]).toMatchObject({status:'ENDED',startedAt:10,lastCombatDay:10,endedAt:10});});
  it.each([{status:'INVALID'},{startedAt:11},{lastCombatDay:9},{endedAt:13},{status:'ENDED',endedAt:9},{status:'ENDED',endedAt:NaN},{status:'ENDED',endedAt:undefined},{hostileCountryPairs:[['BRA','MISSING']]}])('rejects invalid lifecycle %j',patch=>{const r=tick(state(),10).reports![0];expect(()=>readAirSave({wings:[],reports:[{...r,...patch}]},ctx)).toThrow('invalid combat report');});
  it('rejects two ACTIVE reports for the same zone',()=>{const r=tick(state(),10).reports![0];expect(()=>readAirSave({wings:[],reports:[r,{...r,id:'other'}]},ctx)).toThrow('invalid combat report');});
});

describe('Air combat final notifications',()=>{
  it('emits no callback or toast during combat; exactly one at closure, never again',()=>{const callback=vi.fn();let s=tick(state(),10,callback);s=tick(s,11,callback);expect(callback).not.toHaveBeenCalled();expect(airCombatReportToast(s.reports![0],'BRA',ctx.wars)).toBeUndefined();s=quiet(s,12,callback);s=quiet(s,13,callback);expect(callback).not.toHaveBeenCalled();s=quiet(s,14,callback);s=quiet(s,15,callback);expect(callback).toHaveBeenCalledOnce();expect(airCombatReportToast(callback.mock.calls[0][0],'BRA',[])).toContain('Combate aéreo encerrado');});
  it('does not notify if player never participated',()=>{const r=quiet(tick(state(),10),13).reports![0];expect(airCombatReportToast(r,'USA',ctx.wars)).toBeUndefined();});
  it('retains hostile loss summary even after peace',()=>{const r=quiet(tick(state(),10),13).reports![0];expect(airCombatReportToast(r,'BRA',[],'Brasil')).toContain('Brasil: 1 aeronave perdida; inimigos: 1 aeronave perdida');});
  it('uses singular/plural and UTF-8 text, including zero losses',()=>{const active=createAirCombatReport('known',zone.id,10,[{...snapshots[0],aircraftLost:1,finalAircraft:23},{...snapshots[0],wingId:'enemy',countryTag:'ARG',aircraftLost:2,finalAircraft:22}]);const r=finishAirCombatReport(active,13);expect(airCombatReportToast(r,'BRA',ctx.wars,'Brasil')).toBe(`Combate aéreo encerrado em ${zone.name}: Brasil: 1 aeronave perdida; inimigos: 2 aeronaves perdidas.`);expect(airCombatReportToast({...r,participants:r.participants.map(p=>({...p,aircraftLost:0}))},'BRA',ctx.wars)).toContain('0 aeronaves perdidas');});
  it('aggregates the player coalition and hostile countries once',()=>{const report=createAirCombatReport('coalition',zone.id,10,[...snapshots,{...snapshots[0],wingId:'ally',countryTag:'USA',aircraftLost:2},{...snapshots[0],wingId:'enemy',countryTag:'ARG',aircraftLost:4},{...snapshots[0],wingId:'enemy2',countryTag:'BOL',aircraftLost:5}]);const ended=finishAirCombatReport({...report,hostileCountryPairs:[['ARG','BRA'],['BOL','BRA']]},13);expect(airCombatReportToast(ended,'BRA',[],'Brasil')).toContain('Brasil e aliados: 5 aeronaves perdidas; inimigos: 9 aeronaves perdidas');});
});
