import {describe, expect, it} from 'vitest';
import {countries, provincesData} from '../../data/map';
import type {War} from '../../types';
import type {AirState, AirWing} from '../../types/air';
import {AIR_COMBAT_HISTORY_LIMIT} from '../../types/air';
import {airCombatTick, assignAirMission, createInitialAirState, airZoneByProvinceId, cleanupAirState} from '../air';
import {readAirSave} from '../air/save';
import {airCombatReportToast, finishAirCombatReport, createAirCombatReport} from '../air/reports';
const initial = createInitialAirState(countries, provincesData);
const bra = initial.wings.find(w => w.countryTag === 'BRA')!;
const arg = initial.wings.find(w => w.countryTag === 'ARG')!;
const zone = airZoneByProvinceId.get(bra.baseProvinceId)!;
const war: War = {id:'reports-war',attacker:'BRA',defender:'ARG',startDate:{year:1444,month:11,day:11},warScore:0,attackerCasualties:0,defenderCasualties:0,occupiedByAttacker:[],occupiedByDefender:[]};
const ctx = {countries, provinces:provincesData, wars:[war], relations:[]};
const wings = [bra,arg].map(w => assignAirMission(w,'AIR_SUPERIORITY',zone.id,ctx)!);
const state = (ws: AirWing[] = wings): AirState => ({wings:ws,engagements:[]});
const fight = () => airCombatTick(state(),ctx,42);
const report = () => fight().reports![0];
describe('Air Combat Reports V1', () => {
  it('creates one factual report per engagement with zone and day', () => {const r=report();expect(r.zoneId).toBe(zone.id);expect(r.day).toBe(42);expect(fight().reports).toHaveLength(1);});
  it('snapshots wing identity, country, type and mission', () => {for(const w of wings)expect(report().participants.find(p=>p.wingId===w.id)).toMatchObject({wingName:w.name,countryTag:w.countryTag,type:w.type,mission:w.mission});});
  it('captures initial, final and lost aircraft consistently', () => {const next=fight();for(const p of next.reports![0].participants){expect(p.initialAircraft).toBe(wings.find(w=>w.id===p.wingId)!.aircraftCount);expect(p.finalAircraft).toBe(next.wings.find(w=>w.id===p.wingId)!.aircraftCount);expect(p.aircraftLost).toBe(p.initialAircraft-p.finalAircraft);expect(p.aircraftLost).toBe(next.engagements[0].losses[p.wingId]);}});
  it('preserves destroyed wings after combat, cleanup and load', () => {const next=airCombatTick(state([{...wings[0],aircraftCount:1,maxAircraft:1},{...wings[1],aircraftCount:1000,maxAircraft:1000}]),ctx,42);expect(next.wings.some(w=>w.id===bra.id)).toBe(false);const r=next.reports![0];expect(r.participants.find(p=>p.wingId===bra.id)?.finalAircraft).toBe(0);expect(cleanupAirState(next,ctx).reports).toEqual(next.reports);expect(readAirSave({wings:[],reports:[r]},ctx).reports).toEqual([r]);});
  it('aggregates multiple wings per country and type', () => {const r=airCombatTick(state([...wings,{...wings[0],id:'extra'}]),ctx,42).reports![0];expect(r.lossesByCountry.BRA).toBe(r.participants.filter(p=>p.countryTag==='BRA').reduce((s,p)=>s+p.aircraftLost,0));expect(r.lossesByType.FIGHTER).toBe(r.totalAircraftLost);});
  it('preserves coalition participants and countries', () => {const ally={...wings[0],id:'ally',countryTag:'USA'};const alliedCtx={...ctx,provinces:ctx.provinces.map(p=>p.id===ally.baseProvinceId?{...p,owner:'USA'}:p),wars:[war,{...war,id:'coalition',attacker:'USA'}]};const r=airCombatTick(state([ally,wings[1]]),alliedCtx,42).reports![0];expect(r.participants.map(p=>p.countryTag).sort()).toEqual(['ARG','USA']);expect(Object.keys(r.lossesByCountry).sort()).toEqual(['ARG','USA']);});
  it('creates no report without combat', () => {expect(airCombatTick(state(),{...ctx,wars:[]},42).reports).toEqual([]);});
  it('uses deterministic IDs and snapshots regardless of input order', () => {expect(report().id).toBe(`air-battle-42-${zone.id}`);expect(airCombatTick(state([...wings].reverse()),ctx,42).reports).toEqual(fight().reports);});
  it('suffixes duplicate zone/day deterministically', () => {const next=airCombatTick({...state(),reports:[finishAirCombatReport(report(),42)]},ctx,42);expect(next.reports![1].id).toBe(`${report().id}-2`);});
  it('caps history and keeps newest reports', () => {const reports=Array.from({length:AIR_COMBAT_HISTORY_LIMIT+3},(_,day)=>finishAirCombatReport(createAirCombatReport(`old-${day}`,zone.id,day,report().participants),day));const s=airCombatTick({...state(),reports},ctx,200);expect(s.reports).toHaveLength(AIR_COMBAT_HISTORY_LIMIT+1);expect(s.reports![0].day).toBe(3);expect(s.reports![s.reports!.length-1].status).toBe('ACTIVE');});
  it('replaces engagements while keeping reports on peaceful ticks', () => {const next=airCombatTick(fight(),{...ctx,wars:[]},43);expect(next.engagements).toEqual([]);expect(next.reports).toEqual(fight().reports);});
  it('loads reports but discards engagements', () => {const next=fight();const loaded=readAirSave(next,ctx);expect(loaded.engagements).toEqual([]);expect(loaded.reports).toEqual(next.reports);});
  it('accepts negative epoch days used by the historical calendar', () => {const r={...report(),day:-191808,startedAt:-191808,lastCombatDay:-191808};expect(readAirSave({wings:[],reports:[r]},ctx).reports![0].day).toBe(-191808);});
  it('accepts old saves without reports', () => {expect(readAirSave(state(),ctx).reports).toBeUndefined();expect(readAirSave(undefined,ctx).engagements).toEqual([]);});
  it('rebuilds derived totals from snapshots', () => {const r=report();expect(readAirSave({wings:[],reports:[{...r,lossesByCountry:{BRA:999},lossesByType:{},totalAircraftLost:999}]},ctx).reports).toEqual([r]);});
  it.each([{id:3},{zoneId:'missing'},{day:NaN},{day:1.5},{participants:[]},{participants:[{...report().participants[0],type:'INVALID'}]},{participants:[{...report().participants[0],mission:'INVALID'}]},{participants:[{...report().participants[0],initialAircraft:-1}]},{participants:[{...report().participants[0],finalAircraft:999}]},{participants:[{...report().participants[0],aircraftLost:999}]}])('rejects invalid report %j', patch => {expect(()=>readAirSave({wings:[],reports:[{...report(),status:undefined,...patch}]},ctx)).toThrow('invalid combat report');});
  it('does not emit player notifications while active', () => {const messages:string[]=[];airCombatTick(state([...wings,{...wings[0],id:'extra'}]),ctx,42,r=>{const m=airCombatReportToast(r,'BRA',ctx.wars);if(m)messages.push(m);});expect(messages).toHaveLength(0);});
  it('does not notify unrelated players', () => {expect(airCombatReportToast(finishAirCombatReport(report(),45),'USA',ctx.wars)).toBeUndefined();});
  it('summarizes player and enemy losses with friendly zone name', () => {const r=finishAirCombatReport(airCombatTick(fight(),ctx,43).reports![0],45);expect(airCombatReportToast(r,'BRA',ctx.wars)).toBe(`Combate aéreo encerrado em ${zone.name}: BRA: 1 aeronave perdida; inimigos: 1 aeronave perdida.`);});
  it('notifies participating players with zero losses and excludes allied losses', () => {const r=finishAirCombatReport(report(),45);r.participants=r.participants.map(p=>({...p,aircraftLost:0}));r.lossesByCountry.BRA=0;expect(airCombatReportToast(r,'BRA',[])).toContain('0 aeronaves perdidas; inimigos: 0 aeronaves perdidas');});
});
