// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from 'vitest';
import {renderHook,act} from '@testing-library/react';
import {countries,provincesData} from '../../data/map';
import {createInitialAirState,airBases,airZoneByProvinceId,assignAirMission,rebaseAirWing} from '../air';
import {createInitialNavies} from '../naval';
import {createInitialTechState} from '../technology';
import {saveGame,loadGame,getSaveCompatibilityError} from '../saveSystem';
import {useSaveSystem} from '../../hooks/app/useSaveSystem';
afterEach(()=>{localStorage.clear();vi.restoreAllMocks();});
const fixture=()=>({airStateRef:{current:createInitialAirState(countries,provincesData)},navalStateRef:{current:{fleets:createInitialNavies(countries,provincesData),battles:[]}},provincesRef:{current:structuredClone(provincesData)},countriesRef:{current:structuredClone(countries)},armiesRef:{current:[]},warsRef:{current:[]},diplomaticRelationsRef:{current:[]},recruitmentsRef:{current:[]},buildingConstructionsRef:{current:[]},playerTechStateRef:{current:createInitialTechState('BRA')},botTechStatesRef:{current:new Map()},activeBattlesRef:{current:[]},dateRef:{current:{year:1444,month:11,day:11}}});
describe('Air additive Save V3',()=>{
  it('rejects invalid live air state without throwing or writing a slot',()=>{const refs=fixture();refs.airStateRef.current.wings[0].aircraftCount=-1;expect(saveGame(refs,'bad-live')).toBe(false);expect(getSaveCompatibilityError()).toMatch(/Air save/);expect(localStorage.getItem('imperium_save_bad-live')).toBeNull();});
  it('round-trips all initial wings, preserves naval data and player, with static world omitted',()=>{const refs=fixture();expect(saveGame(refs,'air')).toBe(true);const loaded=loadGame('air')!;expect(loaded.version).toBe(3);expect(loaded.air).toEqual(refs.airStateRef.current);expect(loaded.naval).toEqual(refs.navalStateRef.current);expect(loaded.technology.player.countryTag).toBe('BRA');const raw=JSON.parse(localStorage.getItem('imperium_save_air')!);expect(raw.air.bases).toBeUndefined();expect(raw.air.zones).toBeUndefined();expect(loadGame('air')!.air!.wings).toHaveLength(refs.airStateRef.current.wings.length);});
  it('persists ongoing mission and timed rebase',()=>{const refs=fixture();const ctx={provinces:refs.provincesRef.current,countries:refs.countriesRef.current,wars:[],relations:[]};const bra=refs.airStateRef.current.wings.find(w=>w.countryTag==='BRA')!;const target=airBases.find(b=>b.provinceId!==bra.baseProvinceId && provincesData.find(p=>p.id===b.provinceId)?.owner==='BRA')!;refs.airStateRef.current.wings=refs.airStateRef.current.wings.map(w=>w.id===bra.id ? rebaseAirWing(w,target.provinceId,refs.airStateRef.current,ctx)! : w.countryTag==='BRA' && w.type==='CAS' ? assignAirMission(w,'CLOSE_AIR_SUPPORT',airZoneByProvinceId.get(w.baseProvinceId)!.id,ctx)! : w);expect(saveGame(refs,'moving')).toBe(true);expect(loadGame('moving')!.air!.wings).toEqual(refs.airStateRef.current.wings);});
  it('rejects corrupted air data through public load API',()=>{vi.spyOn(console,'error').mockImplementation(()=>{});const refs=fixture();saveGame(refs,'invalid');const raw=JSON.parse(localStorage.getItem('imperium_save_invalid')!);raw.air.wings[0].baseProvinceId='missing';localStorage.setItem('imperium_save_invalid',JSON.stringify(raw));expect(loadGame('invalid')).toBeNull();expect(getSaveCompatibilityError()).toMatch(/Air save/);});
  it('legacy V3 load adds no initial air forces',()=>{const refs=fixture();saveGame(refs,'legacy');const raw=JSON.parse(localStorage.getItem('imperium_save_legacy')!);delete raw.air;localStorage.setItem('imperium_save_legacy',JSON.stringify(raw));expect(loadGame('legacy')!.air!.wings).toEqual([]);});
  it('load hook replaces live air ref and setter without duplicating',()=>{const refs=fixture();saveGame(refs,'hook');const expected=structuredClone(refs.airStateRef.current);refs.airStateRef.current={wings:[],engagements:[]};const setters={setAirState:vi.fn(),setNavalState:vi.fn(),setPlayerCountryTag:vi.fn(),setProvinces:vi.fn(),setAllCountries:vi.fn(),setArmies:vi.fn(),setWars:vi.fn(),setDiplomaticRelations:vi.fn(),setRecruitments:vi.fn(),setBuildingConstructions:vi.fn(),setPlayerTechState:vi.fn(),setBotTechStates:vi.fn(),setActiveBattles:vi.fn(),setDate:vi.fn()};const{result}=renderHook(()=>useSaveSystem(refs,setters,vi.fn()));act(()=>result.current.handleLoad('hook'));expect(refs.airStateRef.current).toEqual(expected);expect(setters.setAirState).toHaveBeenCalledWith(expected);expect(setters.setPlayerCountryTag).toHaveBeenCalledWith('BRA');});
});
