import { describe, expect, it, vi } from 'vitest';
import { countries, provincesData, mapMetadata } from '../../data/map';
import { AIR_BALANCE, AIRCRAFT_TYPES } from '../../data/aircraft';
import type { ActiveBattle, Army, War, DiplomaticRelation } from '../../types';
import type { AirWing, AirState, AircraftType, AirMission } from '../../types/air';
import { airZones, airBases, airZoneByProvinceId, createInitialAirBases, createInitialAirState, airDistance, assignAirMission, cancelAirMission, rebaseAirWing, isAirZoneInRange, canUseAirBase, airMissionEfficiency, getAirZoneControl, getAirSuperiorityModifier, getAirSupportForBattle, airAITick, airCombatTick, airMissionsTick, cleanupAirState, airCounters, type AirContext } from '../air';
import { readAirSave } from '../air/save';
import { createDefaultMarket } from '../market';
import { buildSimulationActivation } from '../simulationActivation';
import { startContinuousBattle, processBattleDay } from '../combat';
import { createGameLoopProfiler } from '../performance/gameLoopProfiler';

const initial=createInitialAirState(countries,provincesData);
const bra=initial.wings.find(w=>w.countryTag==='BRA')!;
const arg=initial.wings.find(w=>w.countryTag==='ARG')!;
const home=airZoneByProvinceId.get(bra.baseProvinceId)!;
const war: War={id:'air-war',attacker:'BRA',defender:'ARG',startDate:{year:1444,month:11,day:11},warScore:0,attackerCasualties:0,defenderCasualties:0,occupiedByAttacker:[],occupiedByDefender:[]};
const context=(wars:War[]=[war],relations:DiplomaticRelation[]=[]):AirContext=>({provinces:structuredClone(provincesData),countries:structuredClone(countries),wars,relations});
const wing=(tag='BRA',type:AircraftType='FIGHTER',overrides:Partial<AirWing>={}):AirWing=>({...bra,id:`test-${tag}-${type}`,countryTag:tag,type,baseProvinceId:tag==='ARG'?arg.baseProvinceId:bra.baseProvinceId,...overrides});
const mission=(w:AirWing,m:AirMission,ctx=context())=>assignAirMission(w,m,home.id,ctx)!;
const state=(...wings:AirWing[]):AirState=>({wings,engagements:[]});
const battle={provinceId:home.provinceIds[0],attackerCountryId:'BRA',defenderCountryId:'ARG'} as ActiveBattle;

describe('Air world and deterministic seeds',()=>{
  it('preserves world-v1, 201 countries and 494 provinces',()=>{expect(mapMetadata.id).toBe('world-v1');expect(countries).toHaveLength(201);expect(provincesData).toHaveLength(494);});
  it('covers every province exactly once',()=>{const ids=airZones.flatMap(z=>z.provinceIds);expect(ids).toHaveLength(494);expect(new Set(ids).size).toBe(494);for(const p of provincesData)expect(airZoneByProvinceId.has(p.id)).toBe(true);});
  it('uses intermediate regional zones with valid centers and symmetric neighbors',()=>{expect(airZones.length).toBeGreaterThan(6);expect(airZones.length).toBeLessThan(150);for(const z of airZones){expect(Number.isFinite(z.center.x+z.center.y)).toBe(true);for(const neighbor of z.neighbors)expect(airZones.find(n=>n.id===neighbor)!.neighbors).toContain(z.id);}});
  it('creates deterministic valid bases and does not seed every province',()=>{expect(createInitialAirBases(countries,provincesData)).toEqual(airBases);expect(createInitialAirBases([...countries].reverse(),[...provincesData].reverse())).toEqual(airBases);expect(airBases.length).toBeLessThan(494);for(const b of airBases)expect(provincesData.some(p=>p.id===b.provinceId)).toBe(true);});
  it('creates deterministic aggregated forces under base capacity',()=>{expect(createInitialAirState(countries,provincesData)).toEqual(initial);expect(createInitialAirState([...countries].reverse(),[...provincesData].reverse())).toEqual(initial);expect(initial.wings.length).toBeGreaterThan(20);expect(initial.wings.length).toBeLessThan(201);expect(readAirSave(initial,context([])).wings).toEqual(initial.wings);});
  it.each(['VAT','MCO','LIE','SMR'])('does not grant an undue air force to %s',tag=>{expect(initial.wings.some(w=>w.countryTag===tag)).toBe(false);expect(airBases.some(b=>provincesData.find(p=>p.id===b.provinceId)?.owner===tag)).toBe(false);});
  it('BRA has fighter, CAS and bomber',()=>expect(initial.wings.filter(w=>w.countryTag==='BRA').map(w=>w.type)).toEqual(['FIGHTER','CAS','BOMBER']));
});
describe('Range, access and rebase',()=>{
  it('uses deterministic non-wrapping projection distance',()=>{expect(airDistance({x:0,y:0},{x:3,y:4})).toBe(5);expect(airDistance({x:0,y:0},{x:5040,y:0})).toBe(5040);});
  it('accepts nearby and rejects distant or missing zones',()=>{expect(isAirZoneInRange(bra,home.id,provincesData)).toBe(true);const far=airZones.find(z=>airDistance(z.center,provincesData.find(p=>p.id===bra.baseProvinceId)!.center)>1100)!;expect(assignAirMission(bra,'AIR_SUPERIORITY',far.id,context())).toBeNull();expect(isAirZoneInRange(bra,'missing',provincesData)).toBe(false);});
  it('requires a real base and owned territory',()=>{expect(canUseAirBase('BRA',bra.baseProvinceId,context())).toBe(true);expect(canUseAirBase('BRA','missing',context())).toBe(false);expect(canUseAirBase('BRA',arg.baseProvinceId,context())).toBe(false);});
  it('permits allied basing at peace but never enemies',()=>{const r:DiplomaticRelation={countryA:'BRA',countryB:'ARG',opinion:50,trust:50,status:'peace',alliance:{since:0}};expect(canUseAirBase('BRA',arg.baseProvinceId,context([],[r]))).toBe(true);expect(canUseAirBase('BRA',arg.baseProvinceId,context([war],[r]))).toBe(false);});
  it('audits directional access: host is grantor',()=>{const r:DiplomaticRelation={countryA:'BRA',countryB:'ARG',opinion:0,trust:50,status:'peace',militaryAccess:['ARG']};expect(canUseAirBase('BRA',arg.baseProvinceId,context([],[r]))).toBe(true);expect(canUseAirBase('ARG',bra.baseProvinceId,context([],[r]))).toBe(false);});
  it('rebases over time, clears mission and arrives',()=>{const target=airBases.find(b=>b.provinceId!==bra.baseProvinceId && provincesData.find(p=>p.id===b.provinceId)?.owner==='BRA')!;const next=rebaseAirWing(mission(bra,'AIR_SUPERIORITY'),target.provinceId,state(bra),context())!;expect(next.status).toBe('REBASING');expect(next.mission).toBeUndefined();let s=state(next);for(let i=0;i<next.rebase!.totalDays;i++)s=airMissionsTick(s,context()).state;expect(s.wings[0].baseProvinceId).toBe(target.provinceId);expect(s.wings[0].rebase).toBeUndefined();});
  it('blocks enemy rebase and duplicate orders',()=>{expect(rebaseAirWing(bra,arg.baseProvinceId,state(bra),context())).toBeNull();expect(rebaseAirWing(bra,bra.baseProvinceId,state(bra),context())).toBeNull();});
  it('reserves destination slots across countries and incoming wings',()=>{const target=airBases.find(b=>b.provinceId!==bra.baseProvinceId && provincesData.find(p=>p.id===b.provinceId)?.owner==='BRA')!;const full=Array.from({length:target.capacity},(_,i)=>wing('BRA','FIGHTER',{id:`full-${i}`,baseProvinceId:target.provinceId}));expect(rebaseAirWing(bra,target.provinceId,state(bra,...full),context())).toBeNull();const incoming=full.map(w=>({...w,baseProvinceId:bra.baseProvinceId,status:'REBASING' as const,rebase:{targetProvinceId:target.provinceId,totalDays:2,daysRemaining:2}}));expect(rebaseAirWing(bra,target.provinceId,state(bra,...incoming),context())).toBeNull();});
});
describe('Mission contracts and activation',()=>{
  const types: AircraftType[]=['FIGHTER','CAS','BOMBER','TRANSPORT_PLANE'];
  const missions: AirMission[]=['AIR_SUPERIORITY','INTERCEPTION','CLOSE_AIR_SUPPORT','BOMBING'];
  it.each(types.flatMap(t=>missions.map(m=>[t,m] as const)))('%s / %s compatibility', (type,m)=>{const w=wing('BRA',type);expect(!!assignAirMission(w,m,home.id,context())).toBe(AIRCRAFT_TYPES[type].missions.includes(m));});
  it('cancels mission without mutating input',()=>{const w=mission(bra,'AIR_SUPERIORITY');const next=cancelAirMission(w);expect(next.status).toBe('READY');expect(next.mission).toBeUndefined();expect(w.mission).toBe('AIR_SUPERIORITY');});
  it('only FULL bots assign decisions; PASSIVE and player stay unchanged',()=>{const ctx=context([]);expect(airAITick(state(bra),new Set(),'USA',ctx,[]).state.wings[0]).toEqual(bra);expect(airAITick(state(bra),new Set(['BRA']),'BRA',ctx,[]).state.wings[0]).toEqual(bra);expect(airAITick(state(bra),new Set(['BRA']),'USA',ctx,[]).state.wings[0].mission).toBe('AIR_SUPERIORITY');});
  it('PASSIVE existing missions and combat continue globally',()=>{const s=state(mission(bra,'AIR_SUPERIORITY'),mission(wing('ARG'),'AIR_SUPERIORITY'));const ai=airAITick(s,new Set(),'USA',context(),[]);expect(ai.state).toEqual(s);const fought=airCombatTick(ai.state,context());expect(fought.engagements).toHaveLength(1);expect(airMissionsTick(fought,context()).state.wings[0].mission).toBe('AIR_SUPERIORITY');});
  it('war participants use existing FULL activation',()=>{const activation=buildSimulationActivation({countries,provinces:provincesData,armies:[],wars:[war],relations:[],playerCountryTag:'USA',date:war.startDate});expect(activation.fullCountryTags.has('BRA')).toBe(true);expect(activation.fullCountryTags.has('ARG')).toBe(true);});
  it('damaged AI rests and cannot assign unsupported transport missions',()=>{expect(airAITick(state(mission(wing('BRA','FIGHTER',{organization:25}),'AIR_SUPERIORITY')),new Set(['BRA']),'USA',context(),[]).state.wings[0].status).toBe('READY');expect(airAITick(state(wing('BRA','TRANSPORT_PLANE')),new Set(['BRA']),'USA',context(),[]).state.wings[0].mission).toBeUndefined();});
  it('AI directs CAS to its own battle and bomber to nearby hostile territory',()=>{const ctx=context();const result=airAITick(state(wing('BRA','CAS'),wing('BRA','BOMBER')),new Set(['BRA']),'USA',ctx,[battle]);expect(result.state.wings[0].mission).toBe('CLOSE_AIR_SUPPORT');expect(result.state.wings[1].mission).toBe('BOMBING');});
});
describe('Air combat and recovery',()=>{
  it('replacement at allied bases pays only the operator resources',()=>{const r:DiplomaticRelation={countryA:'BRA',countryB:'ARG',opinion:50,trust:50,status:'peace',alliance:{since:0}};const ctx=context([],[r]);for(const p of ctx.provinces.filter(p=>p.owner==='BRA')) { if(p.market) { p.market.goods.iron.stock=0;p.market.goods.tools.stock=0; } }const depot=ctx.provinces.find(p=>p.id===bra.baseProvinceId)!;depot.market=createDefaultMarket();depot.market.goods.iron.stock=100;depot.market.goods.tools.stock=100;const host=ctx.provinces.find(p=>p.id===arg.baseProvinceId)!;host.market=createDefaultMarket();host.market.goods.iron.stock=100;host.market.goods.tools.stock=100;const result=airMissionsTick(state(wing('BRA','CAS',{baseProvinceId:arg.baseProvinceId,aircraftCount:20})),ctx);expect(result.state.wings[0].aircraftCount).toBeGreaterThan(20);expect(result.provinces.find(p=>p.id===host.id)!.market!.goods.iron.stock).toBe(100);expect(result.provinces.find(p=>p.id===depot.id)!.market!.goods.iron.stock).toBeLessThan(100);});
  it('applies simultaneous losses, organization and strength damage',()=>{const a=mission(bra,'AIR_SUPERIORITY'),b=mission(wing('ARG'),'AIR_SUPERIORITY');const before=state(a,b);const next=airCombatTick(before,context());expect(next.engagements).toHaveLength(1);for(const w of next.wings){expect(w.aircraftCount).toBeLessThan(24);expect(w.organization).toBeLessThan(100);expect(w.strength).toBeLessThan(100);}expect(before.wings[0].aircraftCount).toBe(24);});
  it('is deterministic under reordered wings and leaves world untouched',()=>{const ctx=context();const before=structuredClone(ctx);const wings=[mission(bra,'AIR_SUPERIORITY'),mission(wing('ARG'),'AIR_SUPERIORITY'),mission(wing('BRA','CAS'),'CLOSE_AIR_SUPPORT')];const a=airCombatTick(state(...wings),ctx),b=airCombatTick(state(...[...wings].reverse()),ctx);expect(a.engagements).toEqual(b.engagements);expect([...a.wings].sort((a,b)=>a.id.localeCompare(b.id))).toEqual([...b.wings].sort((a,b)=>a.id.localeCompare(b.id)));expect(ctx).toEqual(before);});
  it('neutrals and allied countries do not engage',()=>{const a=mission(bra,'AIR_SUPERIORITY'),b=mission(wing('ARG'),'AIR_SUPERIORITY');expect(airCombatTick(state(a,b),context([])).engagements).toEqual([]);});
  it('interception remains idle without bomber/CAS but targets hostile bombing',()=>{const interceptor=mission(bra,'INTERCEPTION'),fighter=mission(wing('ARG'),'AIR_SUPERIORITY');expect(airCombatTick(state(interceptor,{...fighter,organization:10}),context()).engagements).toEqual([]);const bomber=mission(wing('ARG','BOMBER'),'BOMBING');expect(airCombatTick(state(interceptor,bomber),context()).engagements).toHaveLength(1);});
  it('removes zero-aircraft wings',()=>{const a=mission(wing('BRA','FIGHTER',{aircraftCount:1,maxAircraft:1}),'AIR_SUPERIORITY'),b=mission(wing('ARG','FIGHTER',{aircraftCount:1000,maxAircraft:1000}),'AIR_SUPERIORITY');expect(airCombatTick(state(a,b),context()).wings.some(w=>w.id===a.id)).toBe(false);});
  it('recovers organization and strength at friendly bases',()=>{const w=wing('BRA','FIGHTER',{organization:10,strength:40});const next=airMissionsTick(state(w),context()).state.wings[0];expect(next.organization).toBeGreaterThan(10);expect(next.strength).toBeGreaterThan(40);});
  it('replacement pays gold, iron and tools, with immutable inputs',()=>{const ctx=context();const p=ctx.provinces.find(p=>p.id===bra.baseProvinceId)!;p.market=createDefaultMarket();p.market.goods.iron.stock=100;p.market.goods.tools.stock=100;const c=ctx.countries.find(c=>c.tag==='BRA')!;c.resources.gold=100;const before=structuredClone(ctx);const w=wing('BRA','FIGHTER',{aircraftCount:20,strength:60,organization:20});const result=airMissionsTick(state(w),ctx);const n=result.state.wings[0].aircraftCount-20;expect(n).toBeGreaterThan(0);expect(result.countries.find(c=>c.tag==='BRA')!.resources.gold).toBeCloseTo(100-20*AIRCRAFT_TYPES.FIGHTER.maintenance-n*AIR_BALANCE.replacementGold);expect(result.provinces.find(p=>p.id===bra.baseProvinceId)!.market!.goods.iron.stock).toBe(100-n*AIR_BALANCE.replacementIron);expect(result.provinces.find(p=>p.id===bra.baseProvinceId)!.market!.goods.tools.stock).toBe(100-n*AIR_BALANCE.replacementTools);expect(ctx).toEqual(before);});
  it('no resources means no replacement; active missions still have upkeep',()=>{const ctx=context();ctx.countries.find(c=>c.tag==='BRA')!.resources.gold=0;expect(airMissionsTick(state(wing('BRA','FIGHTER',{aircraftCount:10})),ctx).state.wings[0].aircraftCount).toBe(10);const active=mission(bra,'AIR_SUPERIORITY');expect(airMissionsTick(state(active),context()).state.wings[0].organization).toBe(98);});
  it('capture cleanup evacuates safely and respects destination capacity',()=>{const ctx=context();ctx.provinces.filter(p=>p.owner==='BRA').forEach(p=>{p.owner='ARG';});expect(cleanupAirState(state(bra),ctx).wings).toEqual([]);});
  it('aggregates daily profiler counters',()=>{const fought=airCombatTick(state(mission(bra,'AIR_SUPERIORITY'),mission(wing('ARG'),'AIR_SUPERIORITY'),mission(wing('BRA','CAS'),'CLOSE_AIR_SUPPORT'),mission(wing('BRA','BOMBER'),'BOMBING')),context());const counters=airCounters(fought,2);expect(counters.airWings).toBe(4);expect(counters.aircraftLost).toBeGreaterThan(0);expect(counters.airAIBots).toBe(2);expect(counters.casMissions).toBe(1);expect(counters.bombingMissions).toBe(1);});
});
describe('Stable battle APIs and bounded bombing',()=>{
  it('CAS support is bounded across many wings',()=>{const wings=Array.from({length:100},(_,i)=>mission(wing('BRA','CAS',{id:`cas-cap-${i}`}),'CLOSE_AIR_SUPPORT'));expect(getAirSupportForBattle(state(...wings),battle,'BRA',context())).toBe(AIR_BALANCE.casMaxBonus);});
  it('CAS from another participant supports its battle side',()=>{const w=mission(wing('BRA','CAS'),'CLOSE_AIR_SUPPORT');const alliedArmy={id:'allied',owner:'BRA'} as Army;const alliedBattle={...battle,attackerCountryId:'USA',participantArmyIds:['allied'],participantSides:{allied:'attacker' as const}};expect(getAirSupportForBattle(state(w),alliedBattle,'USA',{...context(),armies:[alliedArmy]})).toBeGreaterThan(0);expect(getAirSupportForBattle(state(w),alliedBattle,'BRA',{...context(),armies:[alliedArmy]})).toBeGreaterThan(0);expect(getAirSupportForBattle(state(w),alliedBattle,'ARG',{...context(),armies:[alliedArmy]})).toBe(0);});
  it('no air forces preserves neutral combat modifier',()=>{expect(getAirSuperiorityModifier(state(),battle.provinceId,'BRA',context())).toBe(1);expect(getAirSupportForBattle(state(),battle,'BRA',context())).toBe(0);});
  it('CAS requires involvement, range and minimum efficiency',()=>{const w=mission(wing('BRA','CAS'),'CLOSE_AIR_SUPPORT');expect(getAirSupportForBattle(state(w),battle,'BRA',context())).toBeGreaterThan(0);expect(getAirSupportForBattle(state(w),{...battle,attackerCountryId:'USA'},'BRA',context())).toBe(0);expect(getAirSupportForBattle(state({...w,organization:0}),battle,'BRA',context())).toBe(0);expect(getAirSupportForBattle(state({...w,baseProvinceId:'missing'}),battle,'BRA',context())).toBe(0);});
  it('hostile superiority reduces CAS, friendly fighters restore it',()=>{const cas=mission(wing('BRA','CAS'),'CLOSE_AIR_SUPPORT'),enemy=mission(wing('ARG'),'AIR_SUPERIORITY'),friendly=mission(bra,'AIR_SUPERIORITY');const unopposed=getAirSupportForBattle(state(cas),battle,'BRA',context());expect(getAirSupportForBattle(state(cas,enemy),battle,'BRA',context())).toBeLessThan(unopposed);expect(getAirSupportForBattle(state(cas,enemy,friendly),battle,'BRA',context())).toBe(unopposed);});
  it('control includes quality and clamps land effect',()=>{const a=mission(bra,'AIR_SUPERIORITY'),b=mission(wing('ARG'),'AIR_SUPERIORITY');expect(getAirZoneControl(state(a,b),home.id,'BRA',context()).superiority).toBe(0);expect(getAirZoneControl(state(a,{...b,strength:40}),home.id,'BRA',context()).superiority).toBeGreaterThan(0);expect(getAirSuperiorityModifier(state(a),battle.provinceId,'BRA',context())).toBeCloseTo(1.03);expect(getAirSuperiorityModifier(state(b),battle.provinceId,'BRA',context())).toBeCloseTo(.97);});
  it('bomber harms only hostile owners, once per day and below global cap',()=>{const ctx=context();const target=ctx.provinces.find(p=>home.provinceIds.includes(p.id))!;target.owner='ARG';const bomber=mission(wing('BRA','BOMBER',{aircraftCount:10000,maxAircraft:10000}),'BOMBING',ctx);const before=ctx.countries.find(c=>c.tag==='ARG')!.resources.gold;const next=airMissionsTick(state(bomber),ctx);expect(before-next.countries.find(c=>c.tag==='ARG')!.resources.gold).toBeLessThanOrEqual(AIR_BALANCE.bombingMaxGoldPerCountry);expect(before-next.countries.find(c=>c.tag==='ARG')!.resources.gold).toBeGreaterThan(0);expect(next.provinces.map(p=>p.buildings)).toEqual(ctx.provinces.map(p=>p.buildings));expect(ctx.wars[0].warScore).toBe(0);});
  it('neutral countries are never bombed',()=>{const ctx=context([]);expect(airMissionsTick(state(mission(wing('BRA','BOMBER'),'BOMBING',ctx)),ctx).countries.find(c=>c.tag==='ARG')!.resources).toEqual(ctx.countries.find(c=>c.tag==='ARG')!.resources);});
  it('interception reduces bombing after combat',()=>{const ctx=context();ctx.provinces.find(p=>home.provinceIds.includes(p.id))!.owner='ARG';const bomber=mission(wing('BRA','BOMBER'),'BOMBING',ctx),fighter=mission(wing('ARG'),'INTERCEPTION',ctx);const a=airMissionsTick(state(bomber,cancelAirMission(fighter)),ctx),b=airMissionsTick(airCombatTick(state(bomber,fighter),ctx),ctx);expect(b.countries.find(c=>c.tag==='ARG')!.resources.gold).toBeGreaterThan(a.countries.find(c=>c.tag==='ARG')!.resources.gold);});
  it('land battle with neutral air values exactly matches existing combat',()=>{const p=provincesData.find(p=>p.id===battle.provinceId)!;const army=(id:string,owner:string):Army=>({id,owner,name:id,location:p.id,regiments:[{type:'infantry',strength:1000,morale:100}],destination:null,targetDestination:null,movementProgress:0,movementSpeed:1,position:null,path:[],inCombat:true});const armies=[army('a','BRA'),army('b','ARG')];const b=startContinuousBattle([armies[0]],[armies[1]],p,war.startDate,'land');const neutral=new Map(['BRA','ARG'].map(tag=>[tag,getAirSuperiorityModifier(state(),p.id,tag,context())+getAirSupportForBattle(state(),b,tag,context())]));expect(processBattleDay(b,armies,p,provincesData,neutral)).toEqual(processBattleDay(b,armies,p,provincesData));});
});
describe('Air profiler windows',()=>{
  it('aggregates phases and counters and resets every reporting window',()=>{const report=vi.fn();let time=0;const profiler=createGameLoopProfiler(true,{reportEvery:2,now:()=>++time,report});for(let i=0;i<4;i++){profiler.begin();profiler.endPhase('airAI');profiler.endPhase('airCombat');profiler.endPhase('airMissions');profiler.recordAir(airCounters(state(bra),1));profiler.finish(3,250);}expect(report).toHaveBeenCalledTimes(2);for(const [summary] of report.mock.calls){expect(summary.airCounters.airWings).toBe(2);expect(summary.airCounters.airAIBots).toBe(2);expect(summary.phases.airCombat.count).toBe(2);}});
  it('is inert in production',()=>{const report=vi.fn(),now=vi.fn();const profiler=createGameLoopProfiler(false,{reportEvery:1,now,report});profiler.begin();profiler.recordAir(airCounters(state(bra)));profiler.endPhase('airMissions');profiler.finish(3,250);expect(report).not.toHaveBeenCalled();expect(now).not.toHaveBeenCalled();});
});
describe('Air Save validation',()=>{
  it('legacy missing air is empty and never seeds initial forces',()=>expect(readAirSave(undefined,context())).toEqual(state()));
  it('round-trips missions and rebase state',()=>{const target=airBases.find(b=>b.provinceId!==bra.baseProvinceId && provincesData.find(p=>p.id===b.provinceId)?.owner==='BRA')!;const rebased=rebaseAirWing(bra,target.provinceId,state(bra),context())!;for(const w of [rebased,mission(bra,'AIR_SUPERIORITY')])expect(readAirSave(JSON.parse(JSON.stringify(state(w))),context()).wings[0]).toEqual(w);});
  it.each([
    {baseProvinceId:'missing'},{countryTag:'missing'},{assignedAirZoneId:'missing'},{aircraftCount:-1},{aircraftCount:25},{aircraftCount:0},{maxAircraft:0},{strength:101},{organization:-1},{organization:NaN},{status:'INVALID'},
    {type:'DRONE'},{type:'MISSILE'},{type:'TRANSPORT_PLANE',status:'MISSION',mission:'BOMBING',assignedAirZoneId:home.id},
    {baseProvinceId:arg.baseProvinceId},{mission:'BOMBING',status:'MISSION',assignedAirZoneId:home.id},{status:'MISSION'},{rebase:{targetProvinceId:bra.baseProvinceId,totalDays:1,daysRemaining:1}},
  ])('rejects invalid wing fields %j',override=>expect(()=>readAirSave({wings:[{...bra,...override}]},context())).toThrow(/Air save/));
  it.each([0,-1,1.5,3,NaN])('rejects invalid rebase progress %s',progress=>{const target=airBases.find(b=>b.provinceId!==bra.baseProvinceId && provincesData.find(p=>p.id===b.provinceId)?.owner==='BRA')!;expect(()=>readAirSave({wings:[{...bra,status:'REBASING',rebase:{targetProvinceId:target.provinceId,totalDays:2,daysRemaining:progress}}]},context())).toThrow(/Air save/);});
  it('rejects duplicate IDs and overload',()=>{expect(()=>readAirSave(state(bra,bra),context())).toThrow(/Air save/);const b=airBases.find(b=>b.provinceId===bra.baseProvinceId)!;expect(()=>readAirSave(state(...Array.from({length:b.capacity+1},(_,i)=>({...bra,id:`over-${i}`}))),context())).toThrow(/overloaded/);});
  it('mission efficiency is zero from an inaccessible base',()=>expect(airMissionEfficiency(mission(bra,'AIR_SUPERIORITY'),{...context(),provinces:provincesData.map(p=>p.id===bra.baseProvinceId?{...p,owner:'ARG'}:p)})).toBe(0));
});
