// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import { countries, provincesData } from '../../data/map';
import { createNavalUnit } from '../../data/navalUnits';
import type { DiplomaticRelation, War } from '../../types';
import type { NavalState } from '../../types/naval';
import { amphibiousTick, buildTransportIndexes, disembarkArmy, embarkArmy, fleetTransportCapacity, fleetTransportUsed, LANDING_DAYS, planInvasion, resolveTransportLosses, TRANSPORT_CAPACITY } from '../naval/transport';
import { createInitialNavies, navalAITick, navalCombatTick, navalMovementTick, orderFleetMove, portByProvince, isCoastalProvince } from '../naval';
import { createArmy, getArmyReorganizationBlockReason, issueMoveCommand, processArmyMovement, recoverArmy, calculateArmyMaintenance } from '../military';
import { calculateArmySize, checkAllProvinceCombats } from '../combat';
import { processBattleArrival } from '../../hooks/gameLoop/battleArrivalTick';
import { validateTransportSave } from '../naval/transportSave';
import { readNavalSave } from '../naval/saveCompatibility';
import { loadGame, saveGame } from '../saveSystem';
import { createInitialTechState } from '../technology';
import { processDailyTick } from '../economy';
import { createGameLoopProfiler } from '../performance/gameLoopProfiler';
import { buildSimulationActivation } from '../simulationActivation';
import * as territory from '../territoryTransfer';

const date = { year: 1444, month: 11, day: 1 };
const war: War = { id: 'w', attacker: 'BRA', defender: 'ARG', startDate: date, warScore: 0, attackerCasualties: 0, defenderCasualties: 0, occupiedByAttacker: [], occupiedByDefender: [] };
export function transportFixture(troops = 3600) {
  const fleet = createInitialNavies(countries, provincesData).find(f => f.countryTag === 'BRA')!;
  const target = provincesData.find(p => p.owner === 'ARG' && portByProvince.has(p.id))!;
  const army = createArmy('BRA', '1º Exército', fleet.portProvinceId!);
  army.id = 'army-transport';
  army.regiments = Array.from({ length: Math.ceil(troops / 1000) }, (_, i) => ({ type: 'infantry', strength: Math.min(1000, troops - i * 1000), morale: 100, organization: 100, originProvinceId: fleet.portProvinceId }));
  return { army, fleet, target, ctx: { armies: [army], naval: { fleets: [fleet], battles: [] } as NavalState, provinces: structuredClone(provincesData), wars: [structuredClone(war)], relations: [] as DiplomaticRelation[], actor: 'BRA' } };
}
function aboard(troops = 3600) { const s = transportFixture(troops); s.ctx.armies = embarkArmy(s.ctx, s.army.id, s.fleet.id).armies; return s; }
function landing(troops = 3600) {
  const s = aboard(troops);
  s.ctx.naval = planInvasion(s.ctx, s.fleet.id, [s.army.id], s.target.id).naval;
  s.ctx.naval.fleets[0] = { ...s.fleet, portProvinceId: undefined, locationSeaNodeId: portByProvince.get(s.target.id)!.seaNodeId, status: 'HOLDING' };
  return s;
}
function finish(s = landing()) {
  let result = amphibiousTick(s.ctx.naval, s.ctx.armies, s.ctx.provinces, s.ctx.wars);
  for (let i = 1; i < LANDING_DAYS; i++) result = amphibiousTick(result.naval, result.armies, s.ctx.provinces, s.ctx.wars);
  return result;
}
afterEach(() => { vi.restoreAllMocks(); localStorage.clear(); });
describe('Embark and canonical transport state', () => {
  it('embarks an army at its docked own port, preserving identity, origin and composition', () => { const s = transportFixture(); const result = embarkArmy(s.ctx, s.army.id, s.fleet.id); expect(result.error).toBeUndefined(); expect(result.armies[0]).toMatchObject({ id: s.army.id, owner: 'BRA', embarkedFleetId: s.fleet.id, location: null }); expect(result.armies[0].regiments).toEqual(s.army.regiments); expect(s.ctx.armies[0].location).not.toBeNull(); });
  it('rejects inland armies', () => { const s = transportFixture(); s.army.location = provincesData.find(p => !portByProvince.has(p.id))!.id; expect(embarkArmy(s.ctx, s.army.id, s.fleet.id).error).toContain('não está em porto'); });
  it('rejects foreign fleets', () => { const s = transportFixture(); s.fleet.countryTag = 'ARG'; expect(embarkArmy(s.ctx, s.army.id, s.fleet.id).error).toContain('mesmo Country'); });
  it('rejects fleets without transports', () => { const s = transportFixture(); s.fleet.units = s.fleet.units.filter(u => u.type !== 'TRANSPORT'); expect(embarkArmy(s.ctx, s.army.id, s.fleet.id).error).toContain('sem Transport'); });
  it('reports needed and available capacity', () => { const s = transportFixture(5001); expect(embarkArmy(s.ctx, s.army.id, s.fleet.id).error).toContain('5001'); });
  it('allows exact capacity', () => { const s = aboard(TRANSPORT_CAPACITY); expect(s.ctx.armies[0].embarkedFleetId).toBe(s.fleet.id); });
  it('sums only living transports', () => { const s = transportFixture(); s.fleet.units.push(createNavalUnit('t2', 'TRANSPORT'), { ...createNavalUnit('dead', 'TRANSPORT'), strength: 0 }); expect(fleetTransportCapacity(s.fleet)).toBe(10000); });
  it('supports multiple armies and reserves their shared capacity', () => { const s = aboard(3000); const other = { ...s.army, id: 'other', regiments: [{ ...s.army.regiments[0], strength: 2000 }] }; s.ctx.armies.push(other); s.ctx.armies = embarkArmy(s.ctx, 'other', s.fleet.id).armies; expect(buildTransportIndexes(s.ctx.armies).byFleet.get(s.fleet.id)).toHaveLength(2); expect(fleetTransportUsed(s.ctx.armies)).toBe(5000); });
  it('rejects a fleet at a different port', () => { const s = transportFixture(); s.fleet.portProvinceId = s.target.id; expect(embarkArmy(s.ctx, s.army.id, s.fleet.id).error).toContain('mesmo porto'); });
  it('rejects active battles and duplicate embark', () => { const s = transportFixture(); s.army.inCombat = true; expect(embarkArmy(s.ctx, s.army.id, s.fleet.id).error).toContain('batalha'); const b = aboard(); expect(embarkArmy(b.ctx, b.army.id, b.fleet.id).error).toContain('já está embarcado'); });
  it('cancels terrestrial routes during embark', () => { const s = transportFixture(); Object.assign(s.army, { destination: s.target.id, targetDestination: s.target.id, path: [s.target.id], movementPlan: { waypoints: [s.target.id] }, movementProgress: .5, position: { x: 1, y: 2 } }); const a = embarkArmy(s.ctx, s.army.id, s.fleet.id).armies[0]; expect(a.destination).toBeNull(); expect(a.path).toEqual([]); expect(a.movementPlan).toBeUndefined(); expect(a.position).toBeNull(); });
  it('removes operational land presence and prevents terrestrial orders', () => { const s = aboard(); const a = s.ctx.armies[0]; expect(s.ctx.armies.filter(a => a.location === s.fleet.portProvinceId)).toEqual([]); expect(issueMoveCommand(a, s.target.id, s.ctx.provinces, [])).toBeNull(); expect(processArmyMovement(s.ctx.armies, s.ctx.provinces, []).arrivedArmies).toEqual([]); });
  it('never joins land combat while embarked', () => { const s = aboard(); const defender = { ...s.army, id: 'defender', owner: 'ARG' }; const battles = checkAllProvinceCombats([...s.ctx.armies, defender], s.ctx.provinces, [war], date, []); expect(battles.newBattles).toEqual([]); });
  it('blocks reorganization and manpower recovery at sea', () => { const s = aboard(); const a = s.ctx.armies[0]; expect(getArmyReorganizationBlockReason(a, { armies: s.ctx.armies, provinces: s.ctx.provinces, playerCountryTag: 'BRA' })).toContain('embarcado'); expect(recoverArmy(a, countries.find(c => c.tag === 'BRA')!, s.ctx.provinces.find(p => p.id === s.fleet.portProvinceId)!, s.ctx.armies).reinforced).toBe(0); });
  it('keeps naval movement and cargo identity unchanged', () => { const s = aboard(); const node = portByProvince.get(s.target.id)!.seaNodeId; const f = orderFleetMove(s.fleet, node, 'BRA')!; const moved = navalMovementTick([f], s.ctx.provinces, [], [war]); expect(moved[0]).not.toEqual(f); expect(s.ctx.armies[0].embarkedFleetId).toBe(f.id); expect(s.ctx.armies[0].location).toBeNull(); });
  it('charges normal terrestrial maintenance exactly once with usual modifiers', () => { const s = aboard(); const c = countries.find(c => c.tag === 'BRA')!, p = s.ctx.provinces.filter(p => p.owner === 'BRA'); const cost = calculateArmyMaintenance(s.ctx.armies[0]); const base = processDailyTick(c, p, undefined, false, false, 0).country; const paid = processDailyTick(c, p, undefined, false, false, cost).country; expect(paid.economy.goldExpense - base.economy.goldExpense).toBeGreaterThan(0); expect(paid.resources.gold).toBeLessThan(base.resources.gold); });
});
describe('Disembark and amphibious arrivals', () => {
  it('disembarks in own port and restores movement eligibility', () => { const s = aboard(); const result = disembarkArmy(s.ctx, s.army.id); expect(result.error).toBeUndefined(); expect(result.armies[0].location).toBe(s.fleet.portProvinceId); expect(result.armies[0].embarkedFleetId).toBeUndefined(); });
  it.each(['alliance', 'access'])('allows %s port access', mode => { const s = aboard(); s.ctx.provinces.find(p => p.id === s.fleet.portProvinceId)!.owner = 'ARG'; s.ctx.wars = []; s.ctx.relations = [{ countryA: 'BRA', countryB: 'ARG', status: 'peace', opinion: 0, trust: 50, ...(mode === 'alliance' ? { alliance: { since: 0 } } : { militaryAccess: ['ARG'] }) }]; expect(disembarkArmy(s.ctx, s.army.id).error).toBeUndefined(); });
  it('rejects hostile and inaccessible ports', () => { const s = aboard(); s.ctx.provinces.find(p => p.id === s.fleet.portProvinceId)!.owner = 'ARG'; expect(disembarkArmy(s.ctx, s.army.id).error).toContain('Acesso'); s.ctx.wars = []; expect(disembarkArmy(s.ctx, s.army.id).error).toContain('Acesso'); });
  it('rejects disembark at sea', () => { const s = landing(); expect(disembarkArmy(s.ctx, s.army.id).error).toContain('DOCKED'); });
  it('accepts coastal enemy war target and plans a real sea route', () => { const s = aboard(); const result = planInvasion(s.ctx, s.fleet.id, [s.army.id], s.target.id); expect(result.error).toBeUndefined(); expect(result.naval.invasions?.[0]).toMatchObject({ status: 'SAILING', landingDays: 0, targetProvinceId: s.target.id }); expect(result.naval.fleets[0].route.length).toBeGreaterThan(0); });
  it('rejects inland targets', () => { const s = aboard(); const p = provincesData.find(p => !isCoastalProvince(p.id))!; expect(planInvasion(s.ctx, s.fleet.id, [s.army.id], p.id).error).toContain('não costeiro'); });
  it('explicitly rejects coast without validated landing connection', () => { const s = aboard(); const p = provincesData.find(p => isCoastalProvince(p.id) && !portByProvince.has(p.id))!; expect(planInvasion(s.ctx, s.fleet.id, [s.army.id], p.id).error).toContain('V1 exige'); });
  it('rejects neutral targets and invalid army selection', () => { const s = aboard(); s.ctx.wars = []; expect(planInvasion(s.ctx, s.fleet.id, [s.army.id], s.target.id).error).toContain('Não está em guerra'); s.ctx.wars = [war]; expect(planInvasion(s.ctx, s.fleet.id, ['missing'], s.target.id).error).toContain('Selecione Armies'); });
  it('reports no route when fleet has no valid naval origin', () => { const s = aboard(); s.fleet.portProvinceId = undefined; s.fleet.locationSeaNodeId = 'missing'; expect(planInvasion(s.ctx, s.fleet.id, [s.army.id], s.target.id).error).toContain('Sem rota marítima'); });
  it.each(['COMBAT', 'RETREATING'] as const)('rejects fleet %s', status => { const s = aboard(); s.fleet.status = status; expect(planInvasion(s.ctx, s.fleet.id, [s.army.id], s.target.id).error).toContain('combate ou retirada'); });
  it('does not advance landing before arriving at coastal node', () => { const s = aboard(); const naval = planInvasion(s.ctx, s.fleet.id, [s.army.id], s.target.id).naval; expect(amphibiousTick(naval, s.ctx.armies, s.ctx.provinces, [war]).naval.invasions?.[0].landingDays).toBe(0); });
  it('waits three days and emits ordinary arrival without changing owner', () => { const s = landing(); const first = amphibiousTick(s.ctx.naval, s.ctx.armies, s.ctx.provinces, [war]); expect(first.naval.invasions?.[0]).toMatchObject({ status: 'LANDING', landingDays: 1 }); expect(first.armies[0].location).toBeNull(); const result = finish(s); expect(result.arrivals[0]).toMatchObject({ id: s.army.id, location: s.target.id, embarkedFleetId: undefined }); expect(result.armies).toHaveLength(0); expect(result.counters.completedLandings).toBe(1); expect(s.ctx.provinces.find(p => p.id === s.target.id)!.owner).toBe('ARG'); });
  it('lands only selected army, retaining other cargo', () => { const s = landing(1000); const other = { ...s.ctx.armies[0], id: 'other' }; s.ctx.armies.push(other); const result = finish(s); expect(result.arrivals).toHaveLength(1); expect(result.armies.map(a => a.id)).toEqual(['other']); });
  it('cancels when war ends', () => { const s = landing(); const result = amphibiousTick(s.ctx.naval, s.ctx.armies, s.ctx.provinces, []); expect(result.naval.invasions).toEqual([]); expect(result.armies[0].embarkedFleetId).toBe(s.fleet.id); expect(result.arrivals).toEqual([]); });
  it.each(['BRA', 'CHL'])('revalidates changed owner %s', owner => { const s = landing(); s.ctx.provinces.find(p => p.id === s.target.id)!.owner = owner; expect(amphibiousTick(s.ctx.naval, s.ctx.armies, s.ctx.provinces, [war]).naval.invasions).toEqual([]); });
  it('cancels naval engagement even if it ends in the same tick', () => { const s = landing(); const result = amphibiousTick(s.ctx.naval, s.ctx.armies, s.ctx.provinces, [war], new Set([s.fleet.id])); expect(result.naval.invasions).toEqual([]); expect(result.armies).toEqual(s.ctx.armies); });
  it('revalidates peace without advancing twice in one day', () => { const s = landing(); const first = amphibiousTick(s.ctx.naval, s.ctx.armies, s.ctx.provinces, [war]); const second = amphibiousTick(first.naval, first.armies, s.ctx.provinces, [war], new Set(), false); expect(second.naval.invasions?.[0].landingDays).toBe(1); expect(amphibiousTick(first.naval, first.armies, s.ctx.provinces, [], new Set(), false).naval.invasions).toEqual([]); });
  it.each([false, true])('canonical arrival handles defender=%s', defended => {
    const s = landing(), result = finish(s), defender = { ...s.army, id: 'defender', owner: 'ARG', location: s.target.id };
    const transfer = vi.spyOn(territory, 'transferProvince');
    const arrived = processBattleArrival({ arrivedArmies: result.arrivals, armies: defended ? [defender] : [], provinces: s.ctx.provinces, countries: structuredClone(countries), wars: [war], recruitments: [], buildingConstructions: [], currentActiveBattles: [], snapshot: { date }, playerCountryTag: 'BRA', allCountries: countries, activeBattlesRef: { current: [] }, addLog: vi.fn(), addToast: vi.fn(), setActiveBattles: vi.fn(), cancelProvinceActivities: (_id, _old, _new, rec, cons, provs) => ({ recruitments: rec, constructions: cons, provinces: provs }) });
    expect(arrived.armies.filter(a => a.id === s.army.id)).toHaveLength(1);
    if (defended) { expect(arrived.currentActiveBattles).toHaveLength(1); expect(arrived.provinces.find(p => p.id === s.target.id)!.owner).toBe('ARG'); expect(transfer).not.toHaveBeenCalled(); }
    else { expect(transfer).toHaveBeenCalled(); expect(arrived.provinces.find(p => p.id === s.target.id)!.owner).toBe('BRA'); expect(arrived.countries.find(c => c.tag === 'BRA')!.provinces).toContain(s.target.id); }
  });
  it('PASSIVE ongoing fleet movement and landing keep progressing', () => { const s = landing(); expect(navalAITick(s.ctx.naval.fleets, new Set(), 'USA', s.ctx.provinces, [], [war]).fleets).toEqual(s.ctx.naval.fleets); expect(amphibiousTick(s.ctx.naval, s.ctx.armies, s.ctx.provinces, [war]).counters.activeLandings).toBe(1); });
  it('player and war country remain FULL under existing activation', () => { const s = aboard(); const active = buildSimulationActivation({ countries, provinces: s.ctx.provinces, armies: s.ctx.armies, wars: [war], relations: [], playerCountryTag: 'BRA' }); expect(active.fullCountryTags.has('BRA')).toBe(true); expect(active.fullCountryTags.has('ARG')).toBe(true); });
});
describe('Transport casualties and Naval Combat V1', () => {
  it('applies excess casualties immediately and debits origin population', () => { const s = transportFixture(8000); s.fleet.units.push(createNavalUnit('t2', 'TRANSPORT')); s.ctx.armies = embarkArmy(s.ctx, s.army.id, s.fleet.id).armies; s.fleet.units = s.fleet.units.filter(u => u.id !== 't2'); const before = s.ctx.provinces.find(p => p.id === s.army.location)!.population.total; const result = resolveTransportLosses(s.ctx.naval, s.ctx.armies, s.ctx.provinces); expect(calculateArmySize(result.armies[0])).toBe(5000); expect(result.troopLossesAtSea).toBe(3000); expect(result.provinces.find(p => p.id === s.army.location)!.population.total).toBe(before - 3000); });
  it('distributes losses proportionally across real armies deterministically', () => { const s = aboard(3000); s.fleet.units.push(createNavalUnit('t2', 'TRANSPORT')); const other = { ...s.ctx.armies[0], id: 'other', regiments: [{ ...s.army.regiments[0], strength: 7000 }] }; s.ctx.armies.push(other); s.fleet.units.pop(); const result = resolveTransportLosses(s.ctx.naval, s.ctx.armies, s.ctx.provinces); expect(result.armies.map(calculateArmySize)).toEqual([1500, 3500]); expect(resolveTransportLosses(s.ctx.naval, [...s.ctx.armies].reverse(), s.ctx.provinces).armies.map(calculateArmySize)).toEqual([3500, 1500]); });
  it('all transport losses eliminate armies and leave no cargo reference', () => { const s = aboard(); s.fleet.units = s.fleet.units.filter(u => u.type !== 'TRANSPORT'); const result = resolveTransportLosses(s.ctx.naval, s.ctx.armies, s.ctx.provinces); expect(result.armies).toEqual([]); expect(result.troopLossesAtSea).toBe(3600); expect(buildTransportIndexes(result.armies).byFleet.size).toBe(0); });
  it('fleet destruction eliminates embarked army through canonical casualties', () => { const s = aboard(); s.ctx.naval.fleets = []; const result = resolveTransportLosses(s.ctx.naval, s.ctx.armies, s.ctx.provinces); expect(result.armies).toEqual([]); expect(result.messages[0].message).toContain('Fleet destruída'); });
  it('damaged but living transport retains full V1 capacity', () => { const s = aboard(); s.fleet.units.find(u => u.type === 'TRANSPORT')!.strength = .01; expect(resolveTransportLosses(s.ctx.naval, s.ctx.armies, s.ctx.provinces).troopLossesAtSea).toBe(0); });
  it('does not charge population for ship strength losses or repeat prior casualties', () => { const s = aboard(); s.fleet.units.find(u => u.type === 'TRANSPORT')!.strength -= 20; const result = resolveTransportLosses(s.ctx.naval, s.ctx.armies, s.ctx.provinces); expect(result.provinces).toBe(s.ctx.provinces); s.fleet.units = []; const dead = resolveTransportLosses(s.ctx.naval, s.ctx.armies, s.ctx.provinces); expect(resolveTransportLosses(dead.naval, dead.armies, dead.provinces).troopLossesAtSea).toBe(0); });
  it('naval combat destroys transport then applies land casualties in that tick', () => { const s = landing(); const f = s.ctx.naval.fleets[0]; f.units = [{ ...createNavalUnit('fragile', 'TRANSPORT'), strength: .001 }]; const enemy = { ...f, id: 'enemy', countryTag: 'ARG', units: [createNavalUnit('big', 'BATTLESHIP')] }; const fought = navalCombatTick({ ...s.ctx.naval, fleets: [f, enemy] }, [war], -100, s.ctx.provinces, []); const result = resolveTransportLosses(fought, s.ctx.armies, s.ctx.provinces); expect(result.armies).toEqual([]); expect(result.naval.battles[0].embarkedTroopLosses).toBe(3600); expect(result.naval.battles[0].lossesA + result.naval.battles[0].lossesB).toBeLessThan(3600); });
});
describe('Additive Save V3 and cross-reference validation', () => {
  function refs(s = aboard()) { return { dateRef: { current: date }, provincesRef: { current: s.ctx.provinces }, countriesRef: { current: structuredClone(countries) }, armiesRef: { current: s.ctx.armies }, warsRef: { current: s.ctx.wars }, diplomaticRelationsRef: { current: [] }, recruitmentsRef: { current: [] }, buildingConstructionsRef: { current: [] }, activeBattlesRef: { current: [] }, playerTechStateRef: { current: createInitialTechState('BRA') }, botTechStatesRef: { current: new Map() }, navalStateRef: { current: s.ctx.naval } }; }
  it('persists embark without duplicating or restoring land presence', () => { const r = refs(); expect(saveGame(r, 'embark')).toBe(true); const loaded = loadGame('embark')!; expect(loaded.version).toBe(3); expect(loaded.military.armies).toHaveLength(1); expect(loaded.military.armies[0].location).toBeNull(); expect(loaded.military.armies[0].embarkedFleetId).toBe(r.navalStateRef.current.fleets[0].id); expect(loadGame('embark')!.military.armies).toEqual(loaded.military.armies); });
  it('restores cargo and sailing route/progress together', () => { const s = aboard(); s.ctx.naval = planInvasion(s.ctx, s.fleet.id, [s.army.id], s.target.id).naval; s.ctx.naval.fleets[0].movementProgress = .3; const r = refs(s); expect(saveGame(r, 'sailing')).toBe(true); const loaded = loadGame('sailing')!; expect(loaded.naval).toEqual(s.ctx.naval); expect(loaded.military.armies).toEqual(s.ctx.armies); expect(loaded.military.armies[0].location).toBeNull(); });
  it('restores landing progress and completes exactly once', () => { const s = landing(); const first = amphibiousTick(s.ctx.naval, s.ctx.armies, s.ctx.provinces, [war]); s.ctx.naval = first.naval; const r = refs(s); expect(saveGame(r, 'landing')).toBe(true); const loaded = loadGame('landing')!; const second = amphibiousTick(loaded.naval!, loaded.military.armies, loaded.world.provinces, loaded.military.wars); expect(second.arrivals).toHaveLength(0); const third = amphibiousTick(second.naval, second.armies, loaded.world.provinces, loaded.military.wars); expect(third.arrivals).toHaveLength(1); expect(amphibiousTick(third.naval, third.armies, loaded.world.provinces, loaded.military.wars).arrivals).toHaveLength(0); });
  it.each(['missing', 'foreign', 'capacity', 'duplicate', 'land', 'movement'] as const)('rejects %s transport relation', corruption => { const s = aboard(); if (corruption === 'missing') s.ctx.armies[0].embarkedFleetId = 'missing'; if (corruption === 'foreign') s.fleet.countryTag = 'ARG'; if (corruption === 'capacity') s.fleet.units = []; if (corruption === 'duplicate') s.ctx.armies.push(s.ctx.armies[0]); if (corruption === 'land') s.ctx.armies[0].location = s.army.location; if (corruption === 'movement') s.ctx.armies[0].destination = s.target.id; expect(() => validateTransportSave(s.ctx.armies, s.ctx.naval, s.ctx.provinces)).toThrow(); });
  it.each([-1, 3, NaN, .5])('rejects invalid landing progress %s', progress => { const s = landing(); s.ctx.naval.invasions![0].landingDays = progress; expect(() => readNavalSave(s.ctx.naval)).toThrow(); });
  it('rejects nonexistent target and missing invasion army', () => { const s = landing(); expect(() => validateTransportSave([], s.ctx.naval, s.ctx.provinces)).toThrow(); expect(() => validateTransportSave(s.ctx.armies, s.ctx.naval, s.ctx.provinces.filter(p => p.id !== s.target.id))).toThrow(); });
  it('rejects missing sea node even when an invalid coast also has no port', () => { const s = landing(); const raw = structuredClone(s.ctx.naval) as unknown as { invasions: Record<string, unknown>[] }; raw.invasions[0].targetProvinceId = 'missing'; delete raw.invasions[0].seaNodeId; expect(() => readNavalSave(raw)).toThrow(); });
  it('rejects duplicate cargo selection across invasion orders', () => { const s = landing(); s.ctx.naval.invasions!.push(s.ctx.naval.invasions![0]); expect(() => readNavalSave(s.ctx.naval)).toThrow(); });
  it('rejects corrupted stored refs before migration can hide them', () => { const r = refs(); saveGame(r, 'bad'); const raw = JSON.parse(localStorage.getItem('imperium_save_bad')!); raw.military.armies[0].embarkedFleetId = 'missing'; localStorage.setItem('imperium_save_bad', JSON.stringify(raw)); vi.spyOn(console, 'error').mockImplementation(() => {}); expect(loadGame('bad')).toBeNull(); });
});
describe('Determinism, world and profiler', () => {
  it('preserves all 201 countries and 494 provinces', () => { expect(countries).toHaveLength(201); expect(provincesData).toHaveLength(494); });
  it('repeated landing runs produce identical state', () => { expect(finish()).toEqual(finish()); });
  it('aggregates amphibious counters and resets the report window', () => { const report = vi.fn(); let now = 0; const p = createGameLoopProfiler(true, { report, reportEvery: 1, now: () => now++ }); p.begin(); p.recordAmphibious({ embarkedArmies: 2, transportedTroops: 6000, activeLandings: 1, completedLandings: 1, troopLossesAtSea: 300 }); p.endPhase('amphibious'); p.finish(3, 100); expect(report.mock.calls[0][0].amphibious).toMatchObject({ transportedTroops: 6000, troopLossesAtSea: 300 }); p.begin(); p.finish(3, 100); expect(report.mock.calls[1][0].amphibious.transportedTroops).toBe(0); });
});
