// @vitest-environment jsdom
import { describe, it, expect, vi, afterEach } from 'vitest';
import { transportFixture } from './transportFixture';
import { countries, provincesData } from '../../data/map';
import { amphibiousTick, amphibiousAITick, embarkArmy, planInvasion, fleetTransportCapacity, resolveTransportLosses } from '../naval/transport';
import { getCoastalSeaNodes, isCoastalProvince, isNavigableSeaNode, resolveAmphibiousLandingSeaNode, portByProvince, seaNodeById, navalMovementTick } from '../naval';
import { readNavalSave } from '../naval/saveCompatibility';
import { processBattleArrival } from '../../hooks/gameLoop/battleArrivalTick';
import { saveGame, loadGame } from '../saveSystem';
import { createInitialTechState } from '../technology';
import * as territory from '../territoryTransfer';
const date = { year: 1444, month: 11, day: 1 };
const beach = () => provincesData.find(p => p.owner === 'ARG' && /fuego/i.test(p.id+' '+p.name))!;
function setup(port = false) {
  const s = transportFixture();
  if (!port) s.target = beach();
  s.ctx.armies = embarkArmy(s.ctx, s.army.id, s.fleet.id).armies;
  const plan = planInvasion(s.ctx, s.fleet.id, [s.army.id], s.target.id);
  expect(plan.error).toBeUndefined(); s.ctx.naval = plan.naval;
  return s;
}
function arrive(s: ReturnType<typeof setup>) {
  for (let i=0;i<500 && s.ctx.naval.fleets[0].status==='MOVING';i++) s.ctx.naval.fleets=navalMovementTick(s.ctx.naval.fleets,s.ctx.provinces,[],s.ctx.wars);
  expect(s.ctx.naval.fleets[0].locationSeaNodeId).toBe(s.ctx.naval.invasions![0].seaNodeId);
}
afterEach(()=>{vi.restoreAllMocks();localStorage.clear();});
describe('Amphibious V1.1 beach landing',()=>{
  it('real Tierra del Fuego is coastal without a port and plans a real route',()=>{const s=setup();expect(portByProvince.has(s.target.id)).toBe(false);expect(isCoastalProvince(s.target)).toBe(true);expect(s.ctx.naval.fleets[0].route.length).toBeGreaterThan(0);arrive(s);});
  it.each([true,false])('port=%s duration, save/load, disembark and fleet position',port=>{const s=setup(port);arrive(s);const node=s.ctx.naval.fleets[0].locationSeaNodeId;const days=port?3:5;for(let day=1;day<=days;day++){const r=amphibiousTick(s.ctx.naval,s.ctx.armies,s.ctx.provinces,s.ctx.wars);expect(r.arrivals).toHaveLength(day===days?1:0);s.ctx.naval=readNavalSave(r.naval);s.ctx.armies=r.armies;if(day<days)expect(s.ctx.naval.invasions![0].landingDays).toBe(day);else expect(r.arrivals[0]).toMatchObject({location:s.target.id,embarkedFleetId:undefined});}expect(s.ctx.naval.fleets[0]).toMatchObject({locationSeaNodeId:node,status:'HOLDING',portProvinceId:undefined});expect(portByProvince.has(s.target.id)).toBe(port);expect(fleetTransportCapacity(s.ctx.naval.fleets[0])).toBe(5000);});
  it('uses port node preferentially and deterministic coast order',()=>{const s=setup(true);expect(resolveAmphibiousLandingSeaNode(s.target)?.id).toBe(portByProvince.get(s.target.id)!.seaNodeId);const nodes=getCoastalSeaNodes(beach());expect(nodes.length).toBeGreaterThan(0);expect(resolveAmphibiousLandingSeaNode(beach())?.id).toBe(nodes[0].id);expect(resolveAmphibiousLandingSeaNode(beach().id)).toEqual(resolveAmphibiousLandingSeaNode(beach()));});
  it('rejects inland and unknown/lake-only targets',()=>{expect(isCoastalProvince('sa_bra_mato_grosso')).toBe(false);expect(getCoastalSeaNodes('lake-only')).toEqual([]);expect(resolveAmphibiousLandingSeaNode('lake-only')).toBeUndefined();});
  it.each(['lake','inland'] as const)('explicit %s node is invalid',flag=>{const node=getCoastalSeaNodes(beach())[0];expect(isNavigableSeaNode({...node,[flag]:true})).toBe(false);});
  it('unconnected and lake-labelled nodes are invalid',()=>{const n=getCoastalSeaNodes(beach())[0];expect(isNavigableSeaNode({...n,neighbors:[]})).toBe(false);expect(isNavigableSeaNode({...n,ocean:'Inland lake'})).toBe(false);});
  it('unreachable sailing route and canceled fleet order cancel safely',()=>{const s=setup();s.ctx.naval.fleets[0].route=['missing'];s.ctx.naval.fleets=navalMovementTick(s.ctx.naval.fleets,s.ctx.provinces,[],s.ctx.wars);const r=amphibiousTick(s.ctx.naval,s.ctx.armies,s.ctx.provinces,s.ctx.wars);expect(r.naval.invasions).toEqual([]);expect(r.arrivals).toEqual([]);expect(r.armies[0].embarkedFleetId).toBe(s.fleet.id);});
  it.each(['army','fleet','target','war','capacity','node','cancel'] as const)('safely cancels %s',reason=>{const s=setup();arrive(s);const first=amphibiousTick(s.ctx.naval,s.ctx.armies,s.ctx.provinces,s.ctx.wars);s.ctx.naval=first.naval;if(reason==='army')s.ctx.armies=[];if(reason==='fleet')s.ctx.naval.fleets=[];if(reason==='target')s.ctx.provinces=s.ctx.provinces.filter(p=>p.id!==s.target.id);if(reason==='war')s.ctx.wars=[];if(reason==='capacity')s.ctx.naval.fleets[0].units=[];if(reason==='node')s.ctx.naval.invasions![0].seaNodeId='missing';if(reason==='cancel')s.ctx.naval.invasions=[];const r=amphibiousTick(s.ctx.naval,s.ctx.armies,s.ctx.provinces,s.ctx.wars);expect(r.naval.invasions).toEqual([]);expect(r.arrivals).toEqual([]);if(reason==='fleet'){const losses=resolveTransportLosses(r.naval,r.armies,s.ctx.provinces);expect(losses.armies).toEqual([]);expect(losses.troopLossesAtSea).toBe(3600);}});
  it.each([true,false])('beach arrival uses Battle V3 / transferProvince defended=%s',defended=>{const s=setup();arrive(s);let r=amphibiousTick(s.ctx.naval,s.ctx.armies,s.ctx.provinces,s.ctx.wars);for(let i=1;i<5;i++)r=amphibiousTick(r.naval,r.armies,s.ctx.provinces,s.ctx.wars);const transfer=vi.spyOn(territory,'transferProvince');const result=processBattleArrival({arrivedArmies:r.arrivals,armies:defended?[{...s.army,id:'defender',owner:'ARG',location:s.target.id}]:[],provinces:s.ctx.provinces,countries:structuredClone(countries),wars:s.ctx.wars,recruitments:[],buildingConstructions:[],currentActiveBattles:[],snapshot:{date},playerCountryTag:'BRA',allCountries:countries,activeBattlesRef:{current:[]},addLog:vi.fn(),addToast:vi.fn(),setActiveBattles:vi.fn(),cancelProvinceActivities:(_id,_old,_new,rec,cons,provs)=>({recruitments:rec,constructions:cons,provinces:provs})});expect(result.currentActiveBattles).toHaveLength(defended?1:0);expect(result.provinces.find(p=>p.id===s.target.id)!.owner).toBe(defended?'ARG':'BRA');expect(transfer.mock.calls.length>0).toBe(!defended);});
  it.each([true,false])('Save V3 round-trip preserves port=%s landing and finishes once',port=>{const s=setup(port);arrive(s);const first=amphibiousTick(s.ctx.naval,s.ctx.armies,s.ctx.provinces,s.ctx.wars);const refs={dateRef:{current:date},provincesRef:{current:s.ctx.provinces},countriesRef:{current:structuredClone(countries)},armiesRef:{current:first.armies},warsRef:{current:s.ctx.wars},diplomaticRelationsRef:{current:[]},recruitmentsRef:{current:[]},buildingConstructionsRef:{current:[]},activeBattlesRef:{current:[]},playerTechStateRef:{current:createInitialTechState('BRA')},botTechStatesRef:{current:new Map()},navalStateRef:{current:first.naval}};expect(saveGame(refs,'v11')).toBe(true);const loaded=loadGame('v11')!;expect(loaded.version).toBe(3);expect(loaded.naval).toEqual(first.naval);let r=amphibiousTick(loaded.naval!,loaded.military.armies,loaded.world.provinces,loaded.military.wars);for(let day=2;day<(port?3:5);day++)r=amphibiousTick(r.naval,r.armies,loaded.world.provinces,loaded.military.wars);expect(r.arrivals).toHaveLength(1);expect(amphibiousTick(r.naval,r.armies,loaded.world.provinces,loaded.military.wars).arrivals).toHaveLength(0);});
  it('real Caspian coast is lake-only and cannot be invaded',()=>{const s=setup();s.ctx.naval.invasions=[];expect(isCoastalProvince('as_aze_baku')).toBe(false);expect(planInvasion(s.ctx,s.fleet.id,[s.army.id],'as_aze_baku').error).toContain('lago/interior');});
  it('old port orders without landingType keep three-day compatibility',()=>{const s=setup(true);delete s.ctx.naval.invasions![0].landingType;expect(readNavalSave(s.ctx.naval).invasions![0].landingType).toBeUndefined();});
  it.each([true,false])('AI chooses beach when port unavailable, FULL=%s',full=>{const s=setup();s.ctx.naval.invasions=[];s.ctx.naval.fleets=[s.fleet];const result=amphibiousAITick({...s.ctx,provinces:s.ctx.provinces.filter(p=>p.owner!=='ARG'||p.id===s.target.id)},new Set(full?['BRA']:[]),'USA');expect(result.invasions).toHaveLength(full?1:0);if(full)expect(result.invasions![0].landingType).toBe('BEACH');});
  it('AI prefers a valid port',()=>{const s=setup();s.ctx.naval.invasions=[];s.ctx.naval.fleets=[s.fleet];expect(amphibiousAITick(s.ctx,new Set(['BRA']),'USA').invasions![0].landingType).toBe('PORT');});
  it('rejects a wrong global node even if navigable',()=>{const s=setup();s.ctx.naval.invasions![0].seaNodeId=[...seaNodeById.keys()].find(id=>!getCoastalSeaNodes(s.target).some(n=>n.id===id))!;expect(()=>readNavalSave(s.ctx.naval)).toThrow();});
});
