// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, renderHook, act } from '@testing-library/react';
import { countries, provincesData } from '../../data/map';
import { createNavalUnit } from '../../data/navalUnits';
import { navalCombatTick, seaNodes } from '../naval';
import { endedPlayerNavalBattles, enqueueNavalReports } from '../naval/reports';
import { readNavalSave } from '../naval/saveCompatibility';
import { NavalBattleReportModal } from '../../components/NavalBattleReportModal';
import { NavalBattlePanel } from '../../components/FleetPanel';
import { useGameModals } from '../../hooks/app/useGameModals';
import type { Fleet, NavalBattle, NavalState, NavalUnitType } from '../../types/naval';
import type { War } from '../../types';
afterEach(cleanup);
const node = seaNodes.find(n => n.neighbors.length > 0)!;
const war: War = { id:'w', attacker:'BRA', defender:'ARG', startDate:{year:1444,month:1,day:1}, warScore:0, attackerCasualties:0, defenderCasualties:0, occupiedByAttacker:[], occupiedByDefender:[] };
const fleet = (id:string, tag:string, types:NavalUnitType[]=['CRUISER']):Fleet => ({ id, name:`Frota ${id}`, countryTag:tag, units:types.map((t,i)=>createNavalUnit(`${id}-${i}`,t)), locationSeaNodeId:node.id, route:[], movementProgress:0, status:'HOLDING' });
const tick = (state:NavalState, wars:War[]=[war], day=1) => navalCombatTick(state,wars,day,provincesData,[]);
const start = () => tick({fleets:[fleet('a','BRA',['CRUISER','TRANSPORT','CRUISER']),fleet('b','ARG',['CRUISER','TRANSPORT','CRUISER'])],battles:[]});
const report = (winner?:NavalBattle['winner']) => ({ ...start().battles[0], status:'ENDED' as const, winner });
const show = (battle:NavalBattle, fleets: Fleet[]=[]) => render(<NavalBattleReportModal battle={battle} playerCountryTag="BRA" countries={countries} fleets={fleets} onClose={vi.fn()}/>);
describe('Naval combat reports V1',()=>{
  it('captures fleet names and country tags at creation',()=>{expect(start().battles[0].participantSnapshots?.A[0]).toMatchObject({fleetId:'a',fleetName:'Frota a',countryTag:'BRA'});});
  it('counts initial ships by canonical type',()=>{expect(start().battles[0].participantSnapshots?.A[0].initialShips).toEqual({CRUISER:2,TRANSPORT:1});});
  it('adds reinforcement once in deterministic fleet order',()=>{const s=start();s.fleets.push(fleet('aa','BRA'));const next=tick(s);const again=tick(next,[war],2);expect(again.battles[0].participantSnapshots?.A.map(p=>p.fleetId)).toEqual(['a','aa']);});
  it('keeps initial metadata unchanged through later ticks',()=>{const s=start();s.fleets[0].name='Renamed';expect(tick(s).battles[0].participantSnapshots?.A[0].fleetName).toBe('Frota a');});
  it('retains destroyed fleets and final/lost composition',()=>{const a=fleet('a','BRA',['TRANSPORT','CRUISER']);a.units.forEach(u=>u.strength=.001);const s=tick({fleets:[a,fleet('b','ARG',['BATTLESHIP'])],battles:[]});expect(s.fleets.some(f=>f.id==='a')).toBe(false);expect(s.battles[0].participantSnapshots?.A[0]).toMatchObject({fleetName:'Frota a',initialShips:{TRANSPORT:1,CRUISER:1},finalShips:{},lostShips:{TRANSPORT:1,CRUISER:1}});});
  it('final composition matches surviving units and computes losses per type',()=>{const a=fleet('a','BRA',['TRANSPORT','CRUISER']);a.units[0].strength=.001;const s=tick({fleets:[a,fleet('b','ARG')],battles:[]});expect(s.battles[0].participantSnapshots?.A[0]).toMatchObject({finalShips:{CRUISER:1},lostShips:{TRANSPORT:1,CRUISER:0}});});
  it('aggregate losses remain strength damage rather than sunk ship counts',()=>{const s=start();const remaining=s.fleets[0].units.reduce((sum,u)=>sum+u.strength,0);expect(s.battles[0].lossesA).toBeCloseTo(300-remaining);expect(s.battles[0].lossesA).toBeGreaterThan(0);expect(s.battles[0].participantSnapshots?.A[0].lostShips).toEqual({CRUISER:0,TRANSPORT:0});});
  it.each(['A','B','DRAW'] as const)('preserves combat winner %s',winner=>{const a=fleet('a','BRA'),b=fleet('b','ARG');if(winner!=='A')a.units[0].organization=0;if(winner!=='B')b.units[0].organization=0;expect(tick({fleets:[a,b],battles:[]}).battles[0].winner).toBe(winner);});
  it('hostility end keeps winner undefined and snapshot',()=>{const s=tick(start(),[]);expect(s.battles[0].status).toBe('ENDED');expect(s.battles[0].winner).toBeUndefined();expect(s.battles[0].participantSnapshots?.A[0].fleetName).toBe('Frota a');});
  it('departure ends engagement without inventing winner',()=>{const s=start();s.fleets[0].locationSeaNodeId=node.neighbors[0];const result=tick(s);expect(result.battles[0].status).toBe('ENDED');expect(result.battles[0].winner).toBeUndefined();});
  it('preserves and displays embarked troop losses',()=>{const b=report();b.embarkedTroopLosses=1200;const s=tick({fleets:[],battles:[b]},[]);expect(s.battles[0].embarkedTroopLosses).toBe(1200);show(s.battles[0]);expect(screen.getByText(/Tropas embarcadas perdidas/)).toBeTruthy();});
  it('omits zero embarked losses',()=>{show(report());expect(screen.queryByText(/Tropas embarcadas perdidas/)).toBeNull();});
  it.each([['A','VIT\u00d3RIA NAVAL'],['B','DERROTA NAVAL'],['DRAW','EMPATE'],[undefined,'COMBATE NAVAL ENCERRADO']] as const)('renders result %s', (winner,title)=>{show(report(winner));expect(screen.getByRole('heading',{name:title})).toBeTruthy();});
  it('renders destroyed fleet name, composition, location and duration',()=>{show(report('B'));expect(screen.getByText('Frota a')).toBeTruthy();expect(screen.getAllByText(/Cruzadores: 2/)[0]).toBeTruthy();expect(screen.getByText(/Dura\u00e7\u00e3o: 1 dias/)).toBeTruthy();});
  it('old report without snapshots uses living fleets and destroyed ID fallback',()=>{const b=report();delete b.participantSnapshots;show(b,[fleet('a','BRA')]);expect(screen.getByText('Frota a')).toBeTruthy();expect(screen.getByText('b \u00b7 destru\u00edda')).toBeTruthy();});
  it('historical panel uses snapshots without live fleets',()=>{render(<NavalBattlePanel battle={report()} fleets={[]} onLocate={vi.fn()} onClose={vi.fn()}/>);expect(screen.getByText(/Frota a/)).toBeTruthy();});
  it('old panel without snapshots retains fallback',()=>{const b=report();delete b.participantSnapshots;render(<NavalBattlePanel battle={b} fleets={[]} onLocate={vi.fn()} onClose={vi.fn()}/>);expect(screen.getByText(/a \u00b7 destru\u00edda/)).toBeTruthy();});
  it('detects ACTIVE to ENDED once',()=>{const b=report();expect(endedPlayerNavalBattles([b],new Map([[b.id,'ACTIVE']]),'BRA',[])).toEqual([b]);expect(endedPlayerNavalBattles([b],new Map([[b.id,'ENDED']]),'BRA',[])).toEqual([]);});
  it('detects created and ended same tick',()=>{const b=report();expect(endedPlayerNavalBattles([b],new Map(),'BRA',[])).toEqual([b]);});
  it('ignores unrelated countries and active battles',()=>{expect(endedPlayerNavalBattles([report()],new Map(),'USA',[])).toEqual([]);expect(endedPlayerNavalBattles(start().battles,new Map(),'BRA',[])).toEqual([]);});
  it('old battle participation falls back to fleets',()=>{const b=report();delete b.participantSnapshots;expect(endedPlayerNavalBattles([b],new Map(),'BRA',[fleet('a','BRA')])).toEqual([b]);});
  it('multiple same tick reports stay queued without overwrites or duplicates',()=>{const a=report(),b={...report(),id:'second'};const hook=renderHook(useGameModals);act(()=>hook.result.current.setNavalReports(q=>enqueueNavalReports(q,[a,b])));act(()=>hook.result.current.setNavalReports(q=>enqueueNavalReports(q,[a])));expect(hook.result.current.navalReports).toEqual([a,b]);act(()=>hook.result.current.setNavalReports(q=>q.slice(1)));expect(hook.result.current.navalReports).toEqual([b]);});
  it('round trips snapshot JSON through save validator',()=>{const b=report();expect(readNavalSave(JSON.parse(JSON.stringify({fleets:[],battles:[b]}))).battles[0]).toEqual(b);});
  it('accepts old battle saves without snapshots',()=>{const b=report();delete b.participantSnapshots;expect(readNavalSave({fleets:[],battles:[b]}).battles[0]).toEqual(b);});
  it('rejects invalid snapshot counts',()=>{const b=report();b.participantSnapshots!.A[0].lostShips.CRUISER=-1;expect(()=>readNavalSave({fleets:[],battles:[b]})).toThrow();});
  it('closes with Continuar and Escape',()=>{const close=vi.fn();render(<NavalBattleReportModal battle={report()} playerCountryTag="BRA" countries={countries} onClose={close}/>);fireEvent.click(screen.getByRole('button',{name:'Continuar'}));fireEvent.keyDown(document,{key:'Escape'});expect(close).toHaveBeenCalledTimes(2);});
});
