import { describe, expect, it } from 'vitest';
import { countries } from '../../data/map';
import type { War } from '../../types';
import { army, date, province, relation, war, campaign as combatCampaign, day } from './helpers/southAmericaAudit';
import { getCampaign, getCampaigns, getCampaignCasualties } from '../diplomacy/campaigns';
import { calculateCampaignWarScore, calculateSurrenderProgress, getTerritorialControl, isCapitalOccupied, militaryStrength, processWarResolutionTick, recordBattleWarCasualties, resolveCampaign, shouldUseDefensiveWarPosture, type WarResolutionState } from '../diplomacy/warResolution';
import { makePeace } from '../diplomacy/diplomacyWar';
import { diplomacyDay } from '../diplomacy/diplomacyRelations';
import { checkAllProvinceCombats, startContinuousBattle } from '../combat';
import { transferProvince } from '../territoryTransfer';

export function resolutionWorld(): WarResolutionState {
  const provinces = ['BRA','ARG','CHL','URY'].flatMap(tag => [0,1].map(n => ({...province('sa_bra_parana'), id:`${tag}-${n}`, name:`${tag === 'ARG' ? 'Buenos Aires' : 'Capital'} ${n}`, owner:tag, originalOwner:tag, neighbors:[]})));
  const worldCountries = countries.filter(c => ['BRA','ARG','CHL','URY'].includes(c.tag)).map(c => ({...structuredClone(c), isAnnexed:false, capitalId:`${c.tag}-0`, capital:`${c.tag}-0`, provinces:provinces.filter(p => p.owner === c.tag).map(p => p.id)}));
  const pairs = [['BRA','ARG'],['CHL','ARG'],['BRA','URY'],['CHL','URY']];
  const wars = pairs.map(([a,d],n) => ({...war(a,d),id:n === 0 ? 'campaign' : `pair-${n}`,campaignId:'campaign'}));
  return {provinces,countries:worldCountries,wars,relations:pairs.map(([a,d]) => relation(a,d)),armies:worldCountries.map(c => army(c.tag,`${c.tag}-0`,1)),activeBattles:[],date,recruitments:[],constructions:[]};
}
const root = (s:WarResolutionState) => getCampaign(s.wars,'campaign')!;
const score = (s:WarResolutionState) => calculateCampaignWarScore(root(s),s.provinces,s.countries);
const surrender = (s:WarResolutionState,tag='ARG') => calculateSurrenderProgress(tag,root(s),s.provinces,s.countries,s.armies);
function capture(s:WarResolutionState,id:string,owner:string): WarResolutionState {
  return {...s,...transferProvince(s,id,owner,{date})};
}
const result = () => ({attacker:army('BRA','ARG-0',1),defender:army('ARG','ARG-0',1),attackerCasualties:100,defenderCasualties:200});

describe('War Resolution campaign identity', () => {
  it('identifies root independently of record order', () => { const s=resolutionWorld(); expect(getCampaign([...s.wars].reverse(),'campaign')?.root.id).toBe('campaign'); });
  it('derives leaders and both allied sides without duplicates', () => { const c=root(resolutionWorld()); expect(c.attackerLeader).toBe('BRA'); expect(c.defenderLeader).toBe('ARG'); expect(c.attackerParticipants).toEqual(['BRA','CHL']); expect(c.defenderParticipants).toEqual(['ARG','URY']); });
  it('groups four pair records into one campaign', () => expect(getCampaigns(resolutionWorld().wars)).toHaveLength(1));
  it('never places a self-war country on both sides', () => { const c=getCampaigns([war('BRA','BRA')])[0]; expect(c.inconsistent).toBe(true); expect(c.defenderParticipants).toEqual([]); });
  it('uses standalone legacy war ID as campaign ID', () => expect(getCampaigns([war('BRA','ARG')])[0].id).toBe('BRA-ARG'));
  it('uses sorted fallback when root is absent', () => { const s=resolutionWorld(); expect(getCampaign(s.wars.slice(1).reverse(),'campaign')?.root.id).toBe('pair-1'); });
  it('detects contradictory sides and prevents settlement', () => { const s=resolutionWorld(); s.wars.push({...war('ARG','BRA'),id:'conflict',campaignId:'campaign'}); const c=root(s); expect(c.inconsistent).toBe(true); expect(c.attackerParticipants.some(t => c.defenderParticipants.includes(t))).toBe(false); expect(resolveCampaign(s,c.id,'attacker').result).toBeNull(); });
});

describe('War score and surrender metrics', () => {
  it('starts at zero when both territories are intact', () => expect(score(resolutionWorld())).toBe(0));
  it('does not reward a country for its raw province count', () => { const s=resolutionWorld(); s.provinces.push(...Array.from({length:20},(_,n)=>({...s.provinces[0],id:`extra-${n}`}))); expect(score(s)).toBe(0); });
  it('uses actual owner instead of legacy occupation arrays', () => { const s=resolutionWorld(); s.wars[0].occupiedByAttacker=['ARG-0']; expect(score(s)).toBe(0); expect(score(capture(s,'ARG-1','BRA'))).toBe(25); });
  it('derives territorial ratios from original ownership and present control', () => { const s=capture(resolutionWorld(),'ARG-1','CHL'); expect(getTerritorialControl('ARG',s.provinces)).toEqual({total:2,lost:1,controlled:1,lossRatio:.5}); });
  it('weights occupied capital separately and significantly', () => { const s=capture(resolutionWorld(),'ARG-0','CHL'); expect(isCapitalOccupied(s.countries.find(c=>c.tag==='ARG'),s.provinces)).toBe(true); expect(score(s)).toBe(50); });
  it('accounts for casualties on both campaign sides', () => { const s=resolutionWorld(); s.wars[1].defenderCasualties=300; s.wars[3].attackerCasualties=100; expect(score(s)).toBe(12.5); });
  it.each([['ARG','BRA',100],['BRA','ARG',-100]] as const)('clamps score when %s loses everything', (loser,winner,expected) => { let s=resolutionWorld(); for(const p of s.provinces.filter(p=>p.owner===loser)) s=capture(s,p.id,winner); s.wars[0][loser==='ARG'?'defenderCasualties':'attackerCasualties']=1000; expect(score(s)).toBe(expected); });
  it('increases surrender with territorial loss', () => { const s=resolutionWorld(); expect(surrender(capture(s,'ARG-1','BRA'))).toBeGreaterThan(surrender(s)); });
  it('capital capture alone does not produce instant surrender', () => { const s=capture(resolutionWorld(),'ARG-0','BRA'); expect(surrender(s)).toBe(50); });
  it('absence of troops increases surrender without ending an intact country', () => { const s=resolutionWorld(); s.armies=s.armies.filter(a=>a.owner!=='ARG'); expect(surrender(s)).toBe(20); });
  it('uses actual regiment strength and ignores empty armies', () => { const s=resolutionWorld(); s.armies.push({...army('ARG','ARG-0'),regiments:[]}); expect(militaryStrength(s.armies,['ARG'])).toBe(1000); });
  it('losses and remaining strength increase surrender proportionately', () => { const s=resolutionWorld(); s.wars[0].defenderCasualties=1000; expect(surrender(s)).toBe(15); });
  it('territorial elimination reaches 100 even with surviving armies abroad', () => { let s=resolutionWorld(); for(const p of s.provinces.filter(p=>p.owner==='ARG')) s=capture(s,p.id,'BRA'); expect(surrender(s)).toBe(100); });
  it('clamps combined surrender factors to 100', () => { let s=resolutionWorld(); s.provinces.push(...Array.from({length:18},(_,n)=>({...s.provinces[2],id:`lost-${n}`,owner:'BRA'}))); s=capture(s,'ARG-0','BRA'); s.wars[0].defenderCasualties=100000; expect(surrender(s)).toBe(100); });
  it('normalizes invalid casualty counters without negative or NaN metrics', () => { const s=resolutionWorld(); s.wars[0].defenderCasualties=NaN; s.wars[1].attackerCasualties=-40; expect(score(s)).toBe(0); expect(surrender(s)).toBe(0); });
  it('publishes one coherent score and derived occupation snapshot on all pairs', () => { const s=processWarResolutionTick(capture(resolutionWorld(),'ARG-1','CHL')); expect(s.wars.every(w=>w.warScore===25 && w.occupiedByAttacker.includes('ARG-1'))).toBe(true); expect(s.resolutions).toEqual([]); });
  it('calculates duration from campaign root date', () => { const s=resolutionWorld(); s.date={...date,day:21}; expect(processWarResolutionTick(s).wars.every(w=>w.daysSinceStart===10)).toBe(true); });
});

describe('War casualties are statistics, not another damage application', () => {
  it('records a completed battle on its relevant campaign', () => { const s=resolutionWorld(); const w=recordBattleWarCasualties(s.wars,'b1',result()); expect(getCampaignCasualties(getCampaign(w,'campaign')!)).toMatchObject({attacker:100,defender:200}); });
  it('assigns participant losses to their real countries once', () => { const s=resolutionWorld(); const details=[{id:'a',side:'attacker' as const,final:900,owner:'BRA',loss:100},{id:'ally',side:'attacker' as const,final:700,owner:'CHL',loss:300},{id:'d',side:'defender' as const,final:800,owner:'ARG',loss:200}]; const w=recordBattleWarCasualties(s.wars,'b1',{...result(),participantDetails:[...details,details[1]]}); expect(getCampaignCasualties(getCampaign(w,'campaign')!)).toMatchObject({byCountry:{BRA:100,CHL:300,ARG:200},attacker:400,defender:200}); });
  it('prefers exact combat ledger over report estimates', () => { const s=resolutionWorld(); const w=recordBattleWarCasualties(s.wars,'b1',{...result(),countryCasualties:{BRA:30,CHL:50,ARG:90,URY:10}}); expect(getCampaignCasualties(getCampaign(w,'campaign')!)).toMatchObject({attacker:80,defender:100}); });
  it('does not copy a leader contribution into every allied pair', () => { const s=resolutionWorld(); const w=recordBattleWarCasualties(s.wars,'b1',result()); expect(w.filter(p=>p.attacker==='BRA').reduce((n,p)=>n+p.attackerCasualties,0)).toBe(100); });
  it('deduplicates repeated result after serialization', () => { const w=recordBattleWarCasualties(resolutionWorld().wars,'b1',result()); expect(recordBattleWarCasualties(JSON.parse(JSON.stringify(w)) as War[],'b1',result())).toEqual(w); });
  it('accumulates distinct battle statistics', () => { let w=recordBattleWarCasualties(resolutionWorld().wars,'b1',result()); w=recordBattleWarCasualties(w,'b2',result()); expect(getCampaignCasualties(getCampaign(w,'campaign')!).defender).toBe(400); });
  it('falls back to side totals for legacy reports without loss details', () => { const w=recordBattleWarCasualties(resolutionWorld().wars,'b1',{...result(),participantDetails:[{id:'old',side:'attacker',final:900}]}); expect(getCampaignCasualties(getCampaign(w,'campaign')!).attacker).toBe(100); });
  it('does not mutate armies or incoming war records', () => { const s=resolutionWorld(), before=structuredClone(s); recordBattleWarCasualties(s.wars,'b1',result()); expect(s).toEqual(before); });
  it('ignores unrelated and civil battles', () => { const s=resolutionWorld(); expect(recordBattleWarCasualties(s.wars,'b1',{...result(),attacker:army('rebel_BRA','BRA-0')})).toBe(s.wars); });
  it('integrates actual Combat V2 losses without applying damage twice', () => { const target='sa_arg_chaco', a=army('BRA',target,5),d=army('ARG',target,1); d.regiments=d.regiments.map(r=>({...r,strength:100,morale:1,organization:1})); const battles=checkAllProvinceCombats([a,d],resolutionWorld().provinces.concat(province(target)),[war('BRA','ARG')],date,[]); let s=combatCampaign(battles.armies,[relation('BRA','ARG')],[war('BRA','ARG')]); s.currentActiveBattles=battles.newBattles; for(let n=0;n<60 && !s.battleHistory.length;n++) s=day(s); expect(s.battleHistory).toHaveLength(1); const losses=getCampaignCasualties(getCampaigns(s.wars)[0]); expect(losses.defender).toBeGreaterThan(0); expect(losses.attacker).toBe(5000-militaryStrength(s.armies,['BRA'])); expect(losses.defender).toBe(100-militaryStrength(s.armies,['ARG'])); });
  it('attributes real multi-country combat deltas by owner rather than report representatives', () => { const target='sa_arg_chaco', forces=[army('BRA',target,3),army('CHL',target,3),army('ARG',target,1)]; forces[2].regiments=forces[2].regiments.map(r=>({...r,strength:100,morale:1,organization:1})); const wars=[{...war('BRA','ARG'),campaignId:'BRA-ARG'},{...war('CHL','ARG'),campaignId:'BRA-ARG'}]; const battles=checkAllProvinceCombats(forces,[province(target)],wars,date,[]); let s=combatCampaign(battles.armies,[relation('BRA','ARG'),relation('CHL','ARG')],wars); s.currentActiveBattles=battles.newBattles; s=day(s); expect(s.battleHistory).toHaveLength(1); const losses=getCampaignCasualties(getCampaigns(s.wars)[0]); for(const tag of ['BRA','CHL','ARG']) expect(losses.byCountry[tag]).toBe((tag==='ARG'?100:3000)-militaryStrength(s.armies,[tag])); });
});

describe('Campaign settlement and lifecycle', () => {
  it.each([['ARG','BRA'],['BRA','ARG']] as const)('%s elimination resolves once and %s wins', (loser,winner) => { let s=resolutionWorld(); for(const p of s.provinces.filter(p=>p.owner===loser)) s=capture(s,p.id,winner); const next=processWarResolutionTick(s); expect(next.resolutions).toHaveLength(1); expect(next.resolutions[0]).toMatchObject({winner,loser}); expect(next.wars).toEqual([]); expect(next.countries.find(c=>c.tag===loser)?.isAnnexed).toBe(true); expect(processWarResolutionTick(next).resolutions).toEqual([]); });
  it('keeps winner ally captures and annexes only the defeated leader remainder', () => { const s=capture(resolutionWorld(),'ARG-0','CHL'), next=resolveCampaign(s,'campaign','attacker').state; expect(next.provinces.find(p=>p.id==='ARG-0')?.owner).toBe('CHL'); expect(next.provinces.find(p=>p.id==='ARG-1')?.owner).toBe('BRA'); expect(next.provinces.filter(p=>p.owner==='URY')).toHaveLength(2); expect(next.countries.find(c=>c.tag==='URY')?.isAnnexed).toBe(false); });
  it('restores winning side homeland from any losing participant', () => { const s=capture(resolutionWorld(),'CHL-1','URY'); const next=resolveCampaign(s,'campaign','attacker').state; expect(next.provinces.find(p=>p.id==='CHL-1')).toMatchObject({owner:'CHL',originalOwner:'CHL'}); });
  it('uses canonical transfer indexes and conquest unrest', () => { const next=resolveCampaign(resolutionWorld(),'campaign','attacker').state; for(const c of next.countries) expect([...c.provinces].sort()).toEqual(next.provinces.filter(p=>p.owner===c.tag).map(p=>p.id).sort()); expect(next.provinces.find(p=>p.id==='ARG-1')).toMatchObject({originalOwner:'ARG',owner:'BRA'}); expect(next.provinces.find(p=>p.id==='ARG-1')!.unrest).toBeGreaterThan(0); });
  it('cancels recruitments and construction in settled provinces', () => { const s=resolutionWorld(); s.recruitments=[{provinceId:'ARG-1'} as WarResolutionState['recruitments'][number]]; s.constructions=[{provinceId:'ARG-1'} as WarResolutionState['constructions'][number]]; const next=resolveCampaign(s,'campaign','attacker').state; expect(next.recruitments).toEqual([]); expect(next.constructions).toEqual([]); });
  it('ends every campaign pair and dates the peace relations', () => { const next=resolveCampaign(resolutionWorld(),'campaign','attacker').state; expect(next.wars).toEqual([]); expect(next.relations.every(r=>r.status==='peace' && r.lastWarEndedAt===diplomacyDay(date))).toBe(true); });
  it('removes campaign and pair proposals while retaining unrelated offers', () => { const s=resolutionWorld(); s.relations[0].proposals=['campaign','pair-1','unrelated'].map(id=>({id,kind:'call',from:'BRA',to:'CHL',createdAt:0,expiresAt:999999,warId:id})); expect(resolveCampaign(s,'campaign','attacker').state.relations[0].proposals?.map(p=>p.id)).toEqual(['unrelated']); });
  it('releases invalid battles without manufacturing a combat result', () => { const s=resolutionWorld(); s.armies=s.armies.map(a=>({...a,inCombat:true})); s.activeBattles=[startContinuousBattle([s.armies[0]],[s.armies[1]],s.provinces[2],date,'active')]; const next=resolveCampaign(s,'campaign','attacker').state; expect(next.activeBattles).toEqual([]); expect(next.armies.every(a=>!a.inCombat)).toBe(false); expect(next.armies.slice(0,2).every(a=>!a.inCombat)).toBe(true); });
  it('cancels routes into a former enemy ally after peace', () => { const s=resolutionWorld(); s.armies[0]={...s.armies[0],destination:'URY-0',targetDestination:'URY-0',path:['URY-0']}; const next=resolveCampaign(s,'campaign','attacker').state; expect(next.armies[0]).toMatchObject({destination:null,path:[]}); });
  it('preserves other campaigns and their active hostility', () => { const s=resolutionWorld(); s.wars.push({...war('BRA','URY'),id:'other'}); const next=resolveCampaign(s,'campaign','attacker').state; expect(next.wars.map(w=>w.id)).toEqual(['other']); expect(next.relations.find(r=>r.countryA==='BRA'&&r.countryB==='URY')?.status).toBe('war'); });
  it('shares campaign close with white peace without territorial settlement', () => { const s=resolutionWorld(); const next=makePeace(s,'pair-1'); expect(next.ok).toBe(true); expect(next.wars).toEqual([]); expect(next.relations.every(r=>r.status==='peace')).toBe(true); expect(s.provinces.filter(p=>p.owner==='ARG')).toHaveLength(2); });
  it('does not diplomatically surrender a civil campaign', () => { const s=resolutionWorld(); s.wars=[war('BRA','rebel_BRA')]; expect(processWarResolutionTick(s).wars).toEqual(s.wars); expect(makePeace(s,s.wars[0].id).ok).toBe(false); });
  it('leaves active rebellion government objectives in control', () => { let s=resolutionWorld(); const c=s.countries.find(c=>c.tag==='ARG')!; c.rebellions=[{status:'active'} as NonNullable<typeof c.rebellions>[number]]; for(const p of s.provinces.filter(p=>p.owner==='ARG')) s=capture(s,p.id,'BRA'); expect(processWarResolutionTick(s).resolutions).toEqual([]); });
  it('also rejects direct settlement of a government with active rebellion', () => { const s=resolutionWorld(), c=s.countries.find(c=>c.tag==='ARG')!; c.rebellions=[{status:'active'} as NonNullable<typeof c.rebellions>[number]]; expect(resolveCampaign(s,'campaign','attacker')).toEqual({state:s,result:null}); });
  it('does not transfer territory to a missing campaign leader', () => { const s=resolutionWorld(); s.countries=s.countries.filter(c=>c.tag!=='BRA'); expect(resolveCampaign(s,'campaign','attacker')).toEqual({state:s,result:null}); });
  it('uses war distress for cautious AI posture without automatically making peace', () => { const s=resolutionWorld(); expect(shouldUseDefensiveWarPosture('ARG',s.wars,s.provinces,s.countries,s.armies)).toBe(false); const conquered=capture(s,'ARG-0','BRA'); expect(shouldUseDefensiveWarPosture('ARG',conquered.wars,conquered.provinces,conquered.countries,conquered.armies)).toBe(true); expect(shouldUseDefensiveWarPosture('BRA',conquered.wars,conquered.provinces,conquered.countries,conquered.armies)).toBe(false); });
});
