// @vitest-environment jsdom
import React, {useState} from 'react';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {countries,provincesData,mapMetadata} from '../../../data/map';
import {airBases,airZones,airZoneByProvinceId,createInitialAirState,assignAirMission,isAirZoneInRange} from '../../../engine/air';
import {GameMap} from '../GameMap';
import {AirWingPanel} from '../../AirWingPanel';
import {AirZonePanel} from '../../AirZonePanel';
import {ProvincePanel} from '../../ProvincePanel';
import {createInitialTechState} from '../../../engine/technology';
import {createInitialArmies} from '../../../data/map/initialState';
const state=createInitialAirState(countries,provincesData),wing=state.wings.find(w=>w.countryTag==='BRA')!;
const ctx={countries,provinces:provincesData,wars:[],relations:[]};
const props={provinces:provincesData,countries,armies:[],recruitments:[],buildingConstructions:[],activeBattles:[],selectedProvince:null,hoveredProvince:null,selectedArmy:null,playerCountryTag:'BRA',onProvinceClick:vi.fn(),onProvinceHover:vi.fn(),onArmyClick:vi.fn(),onProvinceRightClick:vi.fn(),airState:state};
afterEach(()=>{cleanup();vi.clearAllMocks();});
function Harness(){const[id,setId]=useState<string|null>(null);return <GameMap {...props} selectedAirWingId={id} onAirWingSelect={setId}/>;}
const view=()=>screen.getByLabelText(mapMetadata.name).getAttribute('viewBox');
const panelProps={wing,state,ctx,owner:true,onMission:vi.fn(),onRebase:vi.fn(),onCancel:vi.fn(),onLocate:vi.fn(),onClose:vi.fn()};
describe('Air UI and shared camera',()=>{
  it('keeps terrestrial army hit targets above zone overlays and selectable in Air Mode',()=>{const army=createInitialArmies(countries).find(a=>a.owner==='BRA')!;const click=vi.fn();const{container}=render(<GameMap {...props} armies={[army]} onArmyClick={click}/>);fireEvent.click(screen.getByLabelText('Air Mode'));const overlay=screen.getByLabelText('Air zones'),layer=container.querySelector('.army-movement-layer')!;expect(overlay.compareDocumentPosition(layer)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/^Brasil: /}));expect(click).toHaveBeenCalledWith(army.id);});
  it('renders only overlay geometry intersecting a zoomed viewport',()=>{const{container}=render(<GameMap {...props} initialViewBox={{x:1700,y:1450,w:500,h:300}}/>);fireEvent.click(screen.getByLabelText('Air Mode'));expect(container.querySelectorAll('.air-zone').length).toBeGreaterThan(0);expect(container.querySelectorAll('.air-zone').length).toBeLessThan(100);});
  it('hides overlays until Air Mode is enabled, then renders zones, bases and wing markers',()=>{render(<Harness/>);expect(screen.queryByLabelText('Air zones')).toBeNull();fireEvent.click(screen.getByLabelText('Air Mode'));expect(screen.getByLabelText('Air zones')).toBeTruthy();expect(screen.getAllByLabelText(/^AirBase /)).toHaveLength(airBases.length);expect(screen.getAllByLabelText(/^AirWing /)).toHaveLength(state.wings.length);});
  it('selects marker and displays aggregated wing details',()=>{render(<Harness/>);fireEvent.click(screen.getByLabelText('Air Mode'));fireEvent.click(screen.getByLabelText(`AirWing ${wing.name}`));expect(screen.getByLabelText('AirWing panel')).toBeTruthy();expect(screen.getByText(/24\/24 aeronaves/)).toBeTruthy();expect(screen.getByLabelText('Assign Mission')).toBeTruthy();});
  it('Locate and F use the existing base camera',()=>{render(<GameMap {...props} selectedAirWingId={wing.id}/>);const before=view();fireEvent.click(screen.getByText('Localizar (F)'));const located=view();expect(located).not.toBe(before);fireEvent.click(screen.getByLabelText('Reset View'));fireEvent.keyDown(window,{key:'f'});expect(view()).toBe(located);});
  it('escape clears air selection and closes the panel',()=>{render(<Harness/>);fireEvent.click(screen.getByLabelText('Air Mode'));fireEvent.click(screen.getByLabelText(`AirWing ${wing.name}`));fireEvent.keyDown(window,{key:'Escape'});expect(screen.queryByLabelText('AirWing panel')).toBeNull();});
  it('retains zoom, pan and one world SVG',()=>{const{container}=render(<Harness/>);fireEvent.click(screen.getByLabelText('Air Mode'));const before=view();fireEvent.keyDown(window,{key:'+'});expect(view()).not.toBe(before);const zoomed=view();fireEvent.keyDown(window,{key:'ArrowLeft'});expect(view()).not.toBe(zoomed);expect(container.querySelectorAll('svg.map__svg')).toHaveLength(1);expect(new Set([...container.querySelectorAll('[data-province-id]')].map(e=>e.getAttribute('data-province-id'))).size).toBe(494);});
  it('does not show air controls in country selection',()=>{render(<GameMap {...props} selectionMode/>);expect(screen.queryByLabelText('Air Mode')).toBeNull();expect(screen.queryByLabelText('Air zones')).toBeNull();});
  it('mission and zone controls issue typed commands',()=>{render(<AirWingPanel {...panelProps}/>);const zone=airZoneByProvinceId.get(wing.baseProvinceId)!;fireEvent.change(screen.getByLabelText('Select AirZone'),{target:{value:zone.id}});fireEvent.change(screen.getByLabelText('Assign Mission'),{target:{value:'INTERCEPTION'}});fireEvent.click(screen.getByText('Atribuir missão'));expect(panelProps.onMission).toHaveBeenCalledWith('INTERCEPTION',zone.id);fireEvent.click(screen.getByText('Cancelar missão / recuperar'));expect(panelProps.onCancel).toHaveBeenCalledTimes(1);});
  it('distant zones are explicitly disabled and marked out of range',()=>{render(<AirWingPanel {...panelProps}/>);const far=airZones.find(z=>!isAirZoneInRange(wing,z.id,provincesData))!;const option=screen.getByRole('option',{name:`${far.name} · fora de alcance`}) as HTMLOptionElement;expect(option.disabled).toBe(true);});
  it('Rebase chooses friendly base and issues command',()=>{render(<AirWingPanel {...panelProps}/>);const target=airBases.find(b=>b.provinceId!==wing.baseProvinceId && provincesData.find(p=>p.id===b.provinceId)?.owner==='BRA')!;fireEvent.change(screen.getByLabelText('Rebase target'),{target:{value:target.provinceId}});fireEvent.click(screen.getByText('Rebase'));expect(panelProps.onRebase).toHaveBeenCalledWith(target.provinceId);});
  it('foreign wing has no owner commands',()=>{render(<AirWingPanel {...panelProps} owner={false}/>);expect(screen.queryByLabelText('Assign Mission')).toBeNull();expect(screen.queryByLabelText('Rebase target')).toBeNull();});
  it('zone panel reports missions, aircraft, superiority and battles',()=>{const zone=airZoneByProvinceId.get(wing.baseProvinceId)!;const w=assignAirMission(wing,'AIR_SUPERIORITY',zone.id,ctx)!;render(<AirZonePanel id={zone.id} state={{wings:[w],engagements:[]}} ctx={ctx} player="BRA" battles={[]} onClose={vi.fn()} onLocate={vi.fn()}/>);expect(screen.getByText(/Aeronaves amigas: 24/)).toBeTruthy();expect(screen.getByText(/Superioridade: 100%/)).toBeTruthy();expect(screen.getByText(/AIR_SUPERIORITY/)).toBeTruthy();});
  it('military tab has compact base section without another tab',()=>{const select=vi.fn();render(<ProvincePanel airState={state} onSelectAirWing={select} province={provincesData.find(p=>p.id===wing.baseProvinceId)!} provinces={provincesData} countries={countries} playerCountry={countries.find(c=>c.tag==='BRA')!} armies={[]} recruitments={[]} buildingConstructions={[]} playerTechState={createInitialTechState('BRA')} botTechStates={new Map()} onClose={vi.fn()} onProvinceClick={vi.fn()} onBuild={vi.fn()} onRecruit={vi.fn()} onCancelRecruitment={vi.fn()} onCancelBuilding={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:/Militar/}));fireEvent.click(screen.getByText(`${wing.name} · 24 aeronaves`));expect(select).toHaveBeenCalledWith(wing.id);expect(screen.queryByRole('button',{name:'Aéreo'})).toBeNull();});
});
