// @vitest-environment jsdom
// These interaction regressions exercise FULL markers; semantic zoom is covered separately.
vi.mock('../markerDetail', async importOriginal => ({ ...await importOriginal<typeof import('../markerDetail')>(), markerDetailLevel: () => 'FULL' }));
import React, { useState } from 'react';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { countries, provincesData } from '../../../data/map';
import { createInitialArmies } from '../../../data/map/initialState';
import { createInitialAirState, airBases, airZones, isAirZoneInRange, airZoneByProvinceId } from '../../../engine/air';
import { createInitialNavies } from '../../../engine/naval';
import { GameMap } from '../GameMap';
import { ProvinceAirProduction } from '../../ProvincePanel/ProvinceAirProduction';
import { startAirProduction } from '../../../engine/air';
import { AIR_PRODUCTION_CONFIG } from '../../../data/aircraft';

const state = createInitialAirState(countries, provincesData), fighter = state.wings.find(w => w.countryTag === 'BRA' && w.type === 'FIGHTER')!;
const cas = state.wings.find(w => w.countryTag === 'BRA' && w.type === 'CAS')!, bomber = state.wings.find(w => w.countryTag === 'BRA' && w.type === 'BOMBER')!;
const army = createInitialArmies(countries).find(a => a.owner === 'BRA')!, fleets = createInitialNavies(countries, provincesData), fleet = fleets.find(f => f.countryTag === 'BRA')!;
const props = { provinces: provincesData, countries, armies: [army], recruitments: [], buildingConstructions: [], activeBattles: [], selectedProvince: null, hoveredProvince: null, selectedArmy: null, playerCountryTag: 'BRA', onProvinceClick: vi.fn(), onProvinceHover: vi.fn(), onArmyClick: vi.fn(), onProvinceRightClick: vi.fn(), onFleetReturn: vi.fn(), onAirMission: vi.fn(), onAirRebase: vi.fn(), airState: state, navalState: { fleets, battles: [] } };
function Harness() { const [air, setAir] = useState<string | null>(null), [land, setLand] = useState<string | null>(null), [naval, setNaval] = useState<string | null>(null); return <GameMap {...props} selectedAirWingId={air} selectedArmy={land} selectedFleetId={naval} onAirWingSelect={id => { setAir(id); if (id) { setLand(null); setNaval(null); } }} onArmyClick={id => { setAir(null); setLand(id); }} onFleetSelect={id => { setAir(null); setNaval(id); }} />; }
const select = (wing = fighter) => fireEvent.click(screen.getByLabelText(`AirWing ${wing.name}`));
const right = (id: string) => fireEvent.contextMenu(document.querySelector(`[data-province-id="${id}"]`)!, { button: 2 });
const mode = () => screen.getByLabelText('Air Mode').getAttribute('aria-pressed');
afterEach(() => { cleanup(); vi.clearAllMocks(); });

describe('direct air map control V1.1', () => {
  it('all Wings are visible with Air Mode off and on; overlays only on', () => { render(<Harness />); expect(mode()).toBe('false'); expect(screen.getAllByLabelText(/^AirWing /)).toHaveLength(state.wings.length); expect(screen.queryByLabelText('Air zones')).toBeNull(); fireEvent.click(screen.getByLabelText('Air Mode')); expect(screen.getByLabelText('Air zones')).toBeTruthy(); expect(screen.getAllByLabelText(/^AirWing /)).toHaveLength(state.wings.length); });
  it('marker click enables Air Mode and opens panel/current zone', () => { const { container } = render(<Harness />); select(); expect(mode()).toBe('true'); expect(screen.getByLabelText('AirWing panel')).toBeTruthy(); expect(container.querySelector('.air-zone--selected')).toBeTruthy(); });
  it('manual Air Mode works without Wing selection', () => { render(<Harness />); fireEvent.click(screen.getByLabelText('Air Mode')); expect(mode()).toBe('true'); expect(screen.queryByLabelText('AirWing panel')).toBeNull(); fireEvent.click(screen.getByLabelText('Air Mode')); expect(mode()).toBe('false'); });
  it('marker stack has distinct offsets and transparent SVG hit targets', () => { const { container } = render(<Harness />); const markers = state.wings.filter(w => w.baseProvinceId === fighter.baseProvinceId).map(w => screen.getByLabelText(`AirWing ${w.name}`)); expect(new Set(markers.map(m => m.getAttribute('transform'))).size).toBe(markers.length); expect(markers.every(m => m.querySelector('[fill="transparent"][pointer-events="all"]'))).toBe(true); expect(container.querySelector('.air-layer--normal')).toBeTruthy(); });
  it('culls offscreen wings in normal mode', () => { render(<GameMap {...props} initialViewBox={{ x: -10000, y: -10000, w: 1, h: 1 }} />); expect(screen.queryAllByLabelText(/^AirWing /)).toHaveLength(0); });
  it.each([[fighter, 'Air Superiority', 'AIR_SUPERIORITY'], [fighter, 'Interception', 'INTERCEPTION'], [cas, 'Close Air Support', 'CLOSE_AIR_SUPPORT'], [bomber, 'Bombing', 'BOMBING']] as const)('%s mission button and right-click derive the correct zone', (wing, label, mission) => { render(<Harness />); select(wing); fireEvent.click(screen.getByRole('button', { name: label })); expect(screen.getByText(/Botão direito em uma província para selecionar/)).toBeTruthy(); right(wing.baseProvinceId); expect(props.onAirMission).toHaveBeenCalledWith(mission, airZoneByProvinceId.get(wing.baseProvinceId)!.id); expect(props.onProvinceRightClick).not.toHaveBeenCalled(); expect(screen.queryByText('Cancelar seleção aérea')).toBeNull(); });
  it('out-of-range retains target and shows specific feedback', () => { render(<Harness />); select(); fireEvent.click(screen.getByText('Air Superiority')); right(airZones.find(z => !isAirZoneInRange(fighter, z.id, provincesData))!.provinceIds[0]); expect(screen.getByText(/AirZone fora do alcance desta AirWing/)).toBeTruthy(); expect(props.onAirMission).not.toHaveBeenCalled(); expect(screen.getByText('Cancelar seleção aérea')).toBeTruthy(); });
  it('zone overlay left click targets actual clicked province', () => { render(<Harness />); select(); fireEvent.click(screen.getByText('Air Superiority')); fireEvent.click(document.querySelector(`[data-air-zone-id][data-province-id="${fighter.baseProvinceId}"]`)!); expect(props.onAirMission).toHaveBeenCalledWith('AIR_SUPERIORITY', airZoneByProvinceId.get(fighter.baseProvinceId)!.id); expect(props.onProvinceClick).not.toHaveBeenCalled(); });
  it('Province without pending command follows normal selection in Air Mode', () => { render(<Harness />); fireEvent.click(screen.getByLabelText('Air Mode')); fireEvent.click(document.querySelector(`[data-air-zone-id][data-province-id="${fighter.baseProvinceId}"]`)!); expect(props.onProvinceClick).toHaveBeenCalledWith(fighter.baseProvinceId); });
  it('completed command restores normal right-click', () => { render(<Harness />); select(); fireEvent.click(screen.getByText('Air Superiority')); right(fighter.baseProvinceId); right(fighter.baseProvinceId); expect(props.onAirMission).toHaveBeenCalledTimes(1); expect(props.onProvinceRightClick).toHaveBeenCalledWith(fighter.baseProvinceId); });
  it('rebase right-click uses exact AirBase and timed engine validation', () => { render(<Harness />); select(); fireEvent.click(screen.getByText('Rebase no mapa')); const base = airBases.find(b => b.provinceId !== fighter.baseProvinceId && provincesData.find(p => p.id === b.provinceId)?.owner === 'BRA')!; right(base.provinceId); expect(props.onAirRebase).toHaveBeenCalledWith(base.provinceId); expect(props.onAirMission).not.toHaveBeenCalled(); });
  it('rebase missing AirBase gives specific feedback', () => { render(<Harness />); select(); fireEvent.click(screen.getByText('Rebase no mapa')); right(provincesData.find(p => !airBases.some(b => b.provinceId === p.id))!.id); expect(screen.getByText(/Esta província não possui AirBase/)).toBeTruthy(); expect(props.onAirRebase).not.toHaveBeenCalled(); });
  it('Army marker exits Air Mode and cancels target', () => { render(<Harness />); select(); fireEvent.click(screen.getByText('Air Superiority')); fireEvent.click(screen.getByRole('button', { name: /^Brasil: / })); expect(mode()).toBe('false'); expect(screen.queryByLabelText('AirWing panel')).toBeNull(); expect(screen.queryByText('Cancelar seleção aérea')).toBeNull(); right(fighter.baseProvinceId); expect(props.onProvinceRightClick).toHaveBeenCalled(); });
  it('Fleet marker exits Air Mode and cancels target', () => { render(<Harness />); select(); fireEvent.click(screen.getByText('Air Superiority')); const marker = document.querySelector(`[data-fleet-id="${fleet.id}"]`); expect(marker).toBeTruthy(); fireEvent.click(marker!); expect(mode()).toBe('false'); expect(screen.queryByLabelText('AirWing panel')).toBeNull(); expect(screen.queryByText('Cancelar seleção aérea')).toBeNull(); });
  it('external Army panel/multiselection updates exit mode', () => { const { rerender } = render(<GameMap {...props} selectedAirWingId={fighter.id} />); fireEvent.click(screen.getByText('Air Superiority')); rerender(<GameMap {...props} selectedAirWingId={null} selectedArmyIds={[army.id]} />); expect(mode()).toBe('false'); expect(screen.queryByText('Cancelar seleção aérea')).toBeNull(); });
  it('external Fleet panel updates exit mode', () => { const { rerender } = render(<GameMap {...props} selectedAirWingId={fighter.id} />); rerender(<GameMap {...props} selectedAirWingId={null} selectedFleetId={fleet.id} />); expect(mode()).toBe('false'); });
  it('another Wing cancels stale command and changes panel', () => { render(<Harness />); select(); fireEvent.click(screen.getByText('Air Superiority')); select(cas); expect(screen.queryByText('Cancelar seleção aérea')).toBeNull(); expect(screen.getByText('Close Air Support')).toBeTruthy(); expect(mode()).toBe('true'); });
  it.each(['Escape', 'close', 'cancel'] as const)('%s cancels pending target without ghost commands', how => { render(<Harness />); select(); fireEvent.click(screen.getByText('Air Superiority')); if (how === 'Escape') fireEvent.keyDown(window, { key: 'Escape' }); if (how === 'close') fireEvent.click(screen.getByLabelText('Close AirWing')); if (how === 'cancel') fireEvent.click(screen.getByText('Cancelar seleção aérea')); expect(screen.queryByText('Cancelar seleção aérea')).toBeNull(); right(fighter.baseProvinceId); expect(props.onAirMission).not.toHaveBeenCalled(); expect(props.onProvinceRightClick).toHaveBeenCalled(); });
  it('incompatible mission has no action and Transport has only rebase', () => { render(<Harness />); select(cas); expect(screen.queryByText('Air Superiority')).toBeNull(); expect(screen.queryByText('Interception')).toBeNull(); });
  it('target command captures naval child contextmenu before naval handlers', () => { render(<GameMap {...props} selectedAirWingId={fighter.id} selectedFleetId={fleet.id} />); fireEvent.click(screen.getByText('Air Superiority')); right(fighter.baseProvinceId); expect(props.onAirMission).toHaveBeenCalled(); expect(props.onFleetReturn).not.toHaveBeenCalled(); expect(props.onProvinceRightClick).not.toHaveBeenCalled(); });
});

describe('compact Aircraft Production UI', () => {
  function fixture() { const province = structuredClone(provincesData.find(p => p.id === fighter.baseProvinceId)!), country = structuredClone(countries.find(c => c.tag === 'BRA')!); province.market!.goods.iron.stock = province.market!.goods.tools.stock = 1000; country.resources.gold = 10000; return { province, country, state: { wings: [], engagements: [] }, actor: 'BRA', onBuild: vi.fn(), onCancel: vi.fn() }; }
  it('shows level, reservations, resources and four build options with costs', () => { const p = fixture(); render(<ProvinceAirProduction {...p} />); expect(screen.getByLabelText('Aircraft Production')).toBeTruthy(); expect(screen.getAllByRole('button', { name: /^Build / })).toHaveLength(4); expect(screen.getByText(/IRON 1000/)).toBeTruthy(); fireEvent.click(screen.getByText('Build Fighter Wing')); expect(p.onBuild).toHaveBeenCalledWith(p.province.id, 'FIGHTER'); });
  it.each(['gold', 'iron', 'tools'] as const)('explains insufficient %s', resource => { const p = fixture(); if (resource === 'gold') p.country.resources.gold = 0; else p.province.market!.goods[resource].stock = 0; render(<ProvinceAirProduction {...p} />); const button = screen.getByText('Build Fighter Wing') as HTMLButtonElement; expect(button.disabled).toBe(true); expect(button.parentElement!.title).toMatch(/insuficiente/); });
  it('shows FIFO progress, days and cancel without refund', () => { const p = fixture(), r = startAirProduction(p.state, [p.province], [p.country], 'BRA', p.province.id, 'FIGHTER'); r.state.production!.queues[p.province.id][0].progress = 20; render(<ProvinceAirProduction {...p} state={r.state} />); expect(screen.getByText(/100 dias restantes/)).toBeTruthy(); expect(screen.getByRole('progressbar').getAttribute('value')).toBe('20'); fireEvent.click(screen.getByLabelText('Cancel air-build-1')); expect(p.onCancel).toHaveBeenCalledWith('air-build-1'); });
  it('completed head visibly waits for capacity', () => { const p = fixture(), r = startAirProduction(p.state, [p.province], [p.country], 'BRA', p.province.id, 'FIGHTER'); r.state.production!.queues[p.province.id][0].progress = AIR_PRODUCTION_CONFIG.FIGHTER.days; render(<ProvinceAirProduction {...p} state={r.state} />); expect(screen.getByText(/Aguardando capacidade/)).toBeTruthy(); });
  it('host resources cannot be used by foreign actor', () => { const p = fixture(); render(<ProvinceAirProduction {...p} actor="ARG" />); expect((screen.getByText('Build Fighter Wing') as HTMLButtonElement).disabled).toBe(true); });
});
