// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { countries, provincesData } from '../../../data/map';
import { createInitialNavies, portByProvince } from '../../../engine/naval';
import { createArmy } from '../../../engine/military';
import { ArmyTransportPanel } from '../../ArmyTransportPanel';
import { FleetPanel, NavalBattlePanel } from '../../FleetPanel';
import { GameMap } from '../GameMap';
import { buildArmyPresentation } from '../mapPresentation';
const fleet = createInitialNavies(countries, provincesData).find(f => f.countryTag === 'BRA')!;
const army = { ...createArmy('BRA', '1º Exército', fleet.portProvinceId!), id: 'transport-army', regiments: [{ type: 'infantry' as const, strength: 3600, morale: 100, originProvinceId: fleet.portProvinceId }] };
const embarked = { ...army, location: null, embarkedFleetId: fleet.id };
const target = provincesData.find(p => p.owner === 'ARG' && portByProvince.has(p.id))!;
const noop = vi.fn();
const mapProps = { provinces: provincesData, countries, armies: [embarked], recruitments: [], buildingConstructions: [], activeBattles: [], selectedProvince: null, hoveredProvince: null, selectedArmy: null, playerCountryTag: 'BRA', onProvinceClick: noop, onProvinceHover: noop, onArmyClick: noop, onProvinceRightClick: noop, selectedFleetId: fleet.id, navalState: { fleets: [fleet], battles: [] }, initialViewBox: { x: 0, y: 100, w: 5040, h: 2300 } };
afterEach(() => { cleanup(); vi.clearAllMocks(); });
describe('Army transport UI', () => {
  it('Army panel exposes fleet choice and capacity with Embark', () => { const embark = vi.fn(); render(<ArmyTransportPanel army={army} armies={[army]} fleets={[fleet]} provinces={provincesData} owner onEmbark={embark} onDisembark={noop}/>); expect(screen.getByLabelText('Embark Fleet').textContent).toContain('Total 5000'); expect(screen.getByLabelText('Embark Fleet').textContent).toContain('Usada 0'); fireEvent.click(screen.getByText('Embark')); expect(embark).toHaveBeenCalledWith(fleet.id); });
  it('offers multiple fleets independently', () => { const other = { ...fleet, id: 'fleet-other', name: 'Segunda Fleet' }, embark = vi.fn(); render(<ArmyTransportPanel army={army} armies={[army]} fleets={[fleet, other]} provinces={provincesData} owner onEmbark={embark} onDisembark={noop}/>); fireEvent.change(screen.getByLabelText('Embark Fleet'), { target: { value: other.id } }); fireEvent.click(screen.getByText('Embark')); expect(embark).toHaveBeenCalledWith(other.id); });
  it('hides Embark inland and for foreign army', () => { const inland = { ...army, location: provincesData.find(p => !portByProvince.has(p.id))!.id }; const { rerender } = render(<ArmyTransportPanel army={inland} armies={[inland]} fleets={[fleet]} provinces={provincesData} owner onEmbark={noop} onDisembark={noop}/>); expect(screen.queryByText('Embark')).toBeNull(); rerender(<ArmyTransportPanel army={army} armies={[army]} fleets={[fleet]} provinces={provincesData} owner={false} onEmbark={noop} onDisembark={noop}/>); expect(screen.queryByText('Embark')).toBeNull(); });
  it('shows embarked fleet and enables port disembark', () => { const disembark = vi.fn(); render(<ArmyTransportPanel army={embarked} armies={[embarked]} fleets={[fleet]} provinces={provincesData} owner onEmbark={noop} onDisembark={disembark}/>); expect(screen.getByText(`Embarked on ${fleet.name}`)).toBeTruthy(); fireEvent.click(screen.getByText('Disembark')); expect(disembark).toHaveBeenCalledOnce(); });
  it('FleetPanel displays transport capacity, cargo, per-army disembark and selection', () => { const disembark = vi.fn(), plan = vi.fn(); render(<FleetPanel fleet={fleet} provinces={provincesData} embarkedArmies={[embarked]} owner onDisembark={disembark} onPlanInvasion={plan} onReturn={noop} onCancel={noop} onLocate={noop} onClose={noop}/>); expect(screen.getByLabelText('Transport Capacity').textContent).toContain('3.600 / 5.000'); fireEvent.click(screen.getByText(`Disembark ${army.name}`)); expect(disembark).toHaveBeenCalledWith(army.id); fireEvent.click(screen.getByLabelText(`Invade with ${army.name}`)); fireEvent.click(screen.getByText('Plan Invasion')); expect(plan).toHaveBeenCalledWith([army.id]); });
  it('Plan Invasion followed by province click sends selected cargo without clearing fleet', () => { const invade = vi.fn(); const { container } = render(<GameMap {...mapProps} onInvasion={invade}/>); fireEvent.click(screen.getByLabelText(`Invade with ${army.name}`)); fireEvent.click(screen.getByText('Plan Invasion')); expect(screen.getByRole('status').textContent).toContain('clique'); fireEvent.click(container.querySelector(`[data-province-id="${target.id}"]`)!); expect(invade).toHaveBeenCalledWith([army.id], target.id); expect(noop).not.toHaveBeenCalled(); });
  it('canceling target selection restores regular province selection', () => { const { container } = render(<GameMap {...mapProps} onInvasion={noop}/>); fireEvent.click(screen.getByLabelText(`Invade with ${army.name}`)); fireEvent.click(screen.getByText('Plan Invasion')); fireEvent.click(screen.getByText('Cancelar seleção')); fireEvent.click(container.querySelector(`[data-province-id="${target.id}"]`)!); expect(mapProps.onProvinceClick).toHaveBeenCalledWith(target.id); });
  it('embarked army has no terrestrial marker/group', () => { expect(buildArmyPresentation([embarked], provincesData).groups).toEqual([]); });
  it('NavalBattlePanel exposes troops aboard and distinct troop losses', () => { render(<NavalBattlePanel fleets={[fleet]} armies={[embarked]} battle={{ id: 'battle', seaNodeId: portByProvince.get(fleet.portProvinceId!)!.seaNodeId, sideA: [fleet.id], sideB: ['enemy'], startedAt: -100, days: 1, lossesA: 10, lossesB: 20, status: 'ENDED', embarkedTroopLosses: 2000 }} onLocate={noop} onClose={noop}/>); expect(screen.getByText(/Troops aboard/).textContent).toContain('3.600'); expect(screen.getByText(/Embarked troop losses/).textContent).toContain('2.000'); });
});
