// @vitest-environment jsdom
import React, { useState } from 'react';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { countries, provincesData, mapMetadata } from '../../../data/map';
import { createInitialNavies, fleetPosition, orderFleetMove, portByProvince, seaNodeById } from '../../../engine/naval';
import { FleetMarker } from '../NavalLayer';
import { FleetPanel, NavalBattlePanel } from '../../FleetPanel';
import { GameMap } from '../GameMap';
import type { NavalBattle } from '../../../types/naval';
import { ProvincePanel } from '../../ProvincePanel';
import { createInitialTechState } from '../../../engine/technology';
const fleets=createInitialNavies(countries,provincesData),fleet=fleets.find(f=>f.countryTag==='BRA')!;
const props={provinces:provincesData,countries,armies:[],recruitments:[],buildingConstructions:[],activeBattles:[],selectedProvince:null,hoveredProvince:null,selectedArmy:null,playerCountryTag:'BRA',onProvinceClick:vi.fn(),onProvinceHover:vi.fn(),onArmyClick:vi.fn(),onProvinceRightClick:vi.fn(),navalState:{fleets:[fleet],battles:[]},initialViewBox:{x:0,y:100,w:5040,h:2300}};
afterEach(cleanup);
function Harness(){const [id,setId]=useState<string|null>(null);return <GameMap {...props} selectedFleetId={id} onFleetSelect={setId}/>;}
const view=()=>screen.getByLabelText(mapMetadata.name).getAttribute('viewBox');
const battle:NavalBattle={id:'battle',seaNodeId:portByProvince.get(fleet.portProvinceId!)!.seaNodeId,sideA:[fleet.id],sideB:['enemy'],startedAt:1,days:3,status:'ACTIVE',lossesA:10,lossesB:20};
describe('Naval UI and shared camera',()=>{
  it('limits naval network rendering to the visible camera area',()=>{const {container}=render(<GameMap {...props} initialViewBox={{x:1700,y:1450,w:500,h:300}}/>);fireEvent.click(screen.getByLabelText('Naval Mode'));expect(container.querySelectorAll('[data-testid="naval-layer"] line').length).toBeLessThan(1000);expect(screen.getAllByLabelText(/^SeaNode /).length).toBeLessThan(200);});
  it('ProvincePanel shows port level, recovery and docked fleets',()=>{const select=vi.fn();render(<ProvincePanel fleets={[fleet]} onSelectFleet={select} province={provincesData.find(p=>p.id===fleet.portProvinceId)!} provinces={provincesData} countries={countries} playerCountry={countries.find(c=>c.tag==='BRA')!} armies={[]} recruitments={[]} buildingConstructions={[]} playerTechState={createInitialTechState('BRA')} botTechStates={new Map()} onClose={vi.fn()} onProvinceClick={vi.fn()} onBuild={vi.fn()} onRecruit={vi.fn()} onCancelRecruitment={vi.fn()} onCancelBuilding={vi.fn()}/>);expect(screen.getByLabelText('Port information').textContent).toContain('nível');expect(screen.getByText(/Recuperação:/)).toBeTruthy();fireEvent.click(screen.getByText(fleet.name));expect(select).toHaveBeenCalledWith(fleet.id);});
  it('FleetMarker renders at the fleet position and selects via click and keyboard',()=>{const select=vi.fn();render(<svg><FleetMarker fleet={fleet} selected={false} color="#fff" scale={1} onSelect={select}/></svg>);const marker=screen.getByRole('button',{name:`Fleet: ${fleet.name}`});const p=fleetPosition(fleet)!;expect(marker.getAttribute('transform')).toBe(`translate(${p.x} ${p.y})`);fireEvent.click(marker);fireEvent.keyDown(marker,{key:'Enter'});expect(select).toHaveBeenCalledTimes(2);});
  it('selecting a fleet opens the panel',()=>{render(<Harness/>);fireEvent.click(screen.getByRole('button',{name:`Fleet: ${fleet.name}`}));expect(screen.getByLabelText('Fleet panel')).toBeTruthy();});
  it('naval network is hidden in normal mode and becomes visible via toggle',()=>{render(<GameMap {...props}/>);expect(screen.queryAllByLabelText(/^SeaNode /)).toHaveLength(0);fireEvent.click(screen.getByLabelText('Naval Mode'));expect(screen.getAllByLabelText(/^SeaNode /).length).toBeGreaterThan(100);expect(screen.getByLabelText('Naval Mode').getAttribute('aria-pressed')).toBe('true');});
  it('a selected fleet exposes SeaNodes without requiring Naval Mode',()=>{render(<GameMap {...props} selectedFleetId={fleet.id}/>);expect(screen.getAllByLabelText(/^SeaNode /).length).toBeGreaterThan(100);});
  it('right-click SeaNode forwards a movement command',()=>{const order=vi.fn();render(<GameMap {...props} selectedFleetId={fleet.id} onFleetOrder={order}/>);const id=portByProvince.get(fleet.portProvinceId!)!.seaNodeId;fireEvent.contextMenu(screen.getByLabelText(`SeaNode ${id}`));expect(order).toHaveBeenCalledWith(id);expect(props.onProvinceRightClick).not.toHaveBeenCalled();});
  it('right-click highlighted port forwards docking command',()=>{const callback=vi.fn();render(<GameMap {...props} selectedFleetId={fleet.id} onFleetReturn={callback}/>);fireEvent.click(screen.getByLabelText('Naval Mode'));const name=provincesData.find(p=>p.id===fleet.portProvinceId)!.name;fireEvent.contextMenu(screen.getByLabelText(`Port: ${name}`));expect(callback).toHaveBeenCalledWith(fleet.portProvinceId);});
  it('Locate and F focus the fleet through the camera API',()=>{render(<GameMap {...props} selectedFleetId={fleet.id}/>);const before=view();fireEvent.click(screen.getByText('Locate (F)'));const located=view();expect(located).not.toBe(before);fireEvent.click(screen.getByLabelText('Reset View'));fireEvent.keyDown(window,{key:'f'});expect(view()).toBe(located);});
  it('owner has Return to Port and Cancel Order actions',()=>{const ret=vi.fn(),cancel=vi.fn();render(<GameMap {...props} selectedFleetId={fleet.id} onFleetReturn={ret} onFleetCancel={cancel}/>);fireEvent.click(screen.getByText('Return to Port'));fireEvent.click(screen.getByText('Cancel Order'));expect(ret).toHaveBeenCalledTimes(1);expect(cancel).toHaveBeenCalledTimes(1);});
  it('foreign fleets cannot issue owner actions',()=>{render(<FleetPanel fleet={fleet} provinces={provincesData} owner={false} onReturn={vi.fn()} onCancel={vi.fn()} onLocate={vi.fn()} onClose={vi.fn()}/>);expect(screen.queryByText('Return to Port')).toBeNull();expect(screen.queryByText('Cancel Order')).toBeNull();});
  it('selected moving fleet renders its planned route',()=>{const id=seaNodeById.get(portByProvince.get(fleet.portProvinceId!)!.seaNodeId)!.neighbors[0],moving=orderFleetMove(fleet,id,'BRA')!;const {container}=render(<GameMap {...props} navalState={{fleets:[moving],battles:[]}} selectedFleetId={fleet.id}/>);expect(container.querySelectorAll('[data-testid="naval-layer"] line').length).toBeGreaterThan(0);});
  it('battle click opens participant/loss/duration panel and focuses the sea node',()=>{render(<GameMap {...props} navalState={{fleets:[fleet],battles:[battle]}}/>);const before=view();fireEvent.click(screen.getByLabelText('Naval battle'));expect(screen.getByLabelText('Naval battle panel')).toBeTruthy();expect(view()).not.toBe(before);expect(screen.getByText(/3 dias/)).toBeTruthy();});
  it('battle report retains destroyed participants',()=>{render(<NavalBattlePanel battle={battle} fleets={[fleet]} onLocate={vi.fn()} onClose={vi.fn()}/>);expect(screen.getByText(/enemy · destruída/)).toBeTruthy();expect(screen.getByText(/Perdas: A 10/)).toBeTruthy();});
  it('keeps one world render with 494 province paths',()=>{const {container}=render(<GameMap {...props}/>);expect(container.querySelectorAll('svg.map__svg')).toHaveLength(1);expect(new Set([...container.querySelectorAll('[data-province-id]')].map(e=>e.getAttribute('data-province-id'))).size).toBe(494);});
});
